const {chromium}=require('/usr/local/lib/node_modules/@playwright/mcp/node_modules/playwright');
const A=require('node:assert/strict'),fs=require('node:fs'),{execFileSync}=require('node:child_process');
const F=require('/assets/club/scored-hands').SCORED_HANDS,P=require('/assets/club/practice-deals.json');
const results=[],errors=[],requests=[];let page,ctx,browser,id,v,finished;
const base='http://127.0.0.1:3000';
async function check(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.stack});console.log('FAIL '+name+' '+e.message);throw e;}finally{fs.writeFileSync('/evidence/browser-results.json',JSON.stringify({kind:'local deterministic checks, not an LLM Oracle score',results,errors},null,2));}}
async function req(method,path,data){
  const headers={};
  if(method==='POST'&&path.startsWith('/api/games')){
    headers['Idempotency-Key']=require('node:crypto').randomUUID();
    const m=path.match(/^\/api\/games\/(G-[^/]+)\//);
    if(m){const r=await ctx.request.get(base+'/api/games/'+m[1]);const v=await r.json();headers['If-Match']=String(v.revision??-1);}
  }
  const r=await ctx.request.fetch(base+path,{method,data,headers});return {status:r.status(),data:await r.json()};
}
async function get(path){const r=await req('GET',path);A.equal(r.status,200);return r.data;}
async function state(s='a'){return get('/api/games/'+id+'?seat='+s);}
async function action(selector,path){const wait=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===path);await page.locator(selector).click();const r=await wait;const data=await r.json();A(r.ok(),JSON.stringify(data));await page.waitForFunction(()=>!document.querySelector('main').hasAttribute('aria-busy'));return data;}
async function seat(s){if(await page.locator('#seatb').isChecked()!==(s==='b')){const wait=page.waitForResponse(r=>r.request().method()==='GET'&&r.url().includes('/api/games/'+id+'?seat='+s));await page.locator('#seatb').setChecked(s==='b');await wait;}await page.waitForFunction(s=>document.querySelector('#turnhint').textContent.includes('Seat '+s.toUpperCase()),s);}
async function create(p='pegging',a=0,b=0){await page.selectOption('#practice-deal',p);await page.fill('#start-a',String(a));await page.fill('#start-b',String(b));v=await action('#fixed-practice','/api/games');id=v.id;A.equal(v.phase,'discard');return v;}
async function discard(s,cards){await seat(s);for(const c of cards)await page.locator('#hand [data-card="'+c+'"]').click();v=await action('#discard','/api/games/'+id+'/discard');return v;}
async function ready(p='pegging',a=0,b=0){await create(p,a,b);for(const s of ['a','b'])await discard(s,P[p][s].slice(4));v=await action('#cut','/api/games/'+id+'/cut');return v;}
async function play(s,c){await seat(s);v=await action('#hand [data-card="'+c+'"]','/api/games/'+id+'/play');return v;}
const journey=[['b','5S'],['a','7H'],['b','6H'],['a','TH'],['b','AC'],['a','2S'],['b','9D'],['a','3S']];
const pairs=[['b','5S'],['a','5H'],['b','5D'],['a','5C'],['b','2H'],['a','2S'],['b','3H'],['a','3S']];
async function sequence(moves){for(const [s,c] of moves)await play(s,c);}
async function refuse(path,body){const before=await state();const r=await req('POST','/api/games/'+id+'/'+path,body);A(r.status>=400&&r.status<500,JSON.stringify(r));A(r.data.error);A.deepEqual(await state(),before);}
async function shot(name){await page.screenshot({path:'/evidence/'+name+'.png',fullPage:true});}
async function noOverflow(){A(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'horizontal overflow');}
function perms(a){return a.length?a.flatMap((c,i)=>perms(a.filter((_,j)=>i!==j)).map(t=>[c,...t])):[[]];}
(async()=>{browser=await chromium.launch({executablePath:'/usr/local/bin/chromium',headless:true,args:['--no-sandbox']});ctx=await browser.newContext({viewport:{width:1280,height:800},reducedMotion:'reduce'});page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto(base);await page.waitForSelector('#ladder tr');
await check('live page, exact seeded ladder, empty states and SVG board',async()=>{A.equal((await get('/api/health')).ok,true);const l=await get('/api/ladder'),seed=require('/assets/club/records/gambit_seed_data.json');A.deepEqual([...l.members].sort((a,b)=>a.no.localeCompare(b.no)),[...seed.members].sort((a,b)=>a.no.localeCompare(b.no)));A.deepEqual(l.games.map(g=>({...g,finished:Boolean(g.finished)})).sort((a,b)=>a.id.localeCompare(b.id)),seed.games.map(g=>({...g,finished:Boolean(g.finished)})).sort((a,b)=>a.id.localeCompare(b.id)));A.equal((await get('/api/games')).games.length,0);A.equal((await req('GET','/api/games/G-1183')).status,404);A.equal(await page.locator('#new').isEnabled(),true);A.equal(await page.locator('#cut').isDisabled(),true);A.equal(await page.locator('#board circle').count(),244);await noOverflow();await shot('desktop-idle');});
await check('visible hand/play benches with breakdowns',async()=>{const h=await action('#hand-score-form button','/api/score');A.equal(h.total,29);A.deepEqual(h.breakdown,{fifteens:16,pairs:12,runs:0,flush:0,nobs:1});A.match(await page.locator('#hand-score-result').innerText(),/29 points/);const p=await action('#play-score-form button','/api/play/score');A.equal(p.points,3);A.equal(p.total,18);await shot('desktop-bench');});
await check('visible representative hand totals, overlap, ace, nobs and both flush modes',async()=>{const cases=[['4S 5H 5D 6C','9C',false,14,{fifteens:6,pairs:2,runs:6,flush:0,nobs:0}],['2S 5S 8S KS','9H',false,8,{flush:4}],['2S 5S 8S KS','9H',true,4,{flush:0}],['2S 5S 8S KS','9S',false,9,{flush:5}],['2S 5S 8S KS','9S',true,9,{flush:5}],['AS 2H 3D JC','KC',false,8,{runs:3,fifteens:4,nobs:1}],['JS QH KD AC','2C',false,3,{runs:3}],['JS 2H 4D 8C','9S',false,3,{nobs:1}],['JH 2H 4D 8C','9S',false,2,{nobs:0}]];const zero=F.find(f=>f.total===0);cases.push([zero.hand.join(' '),zero.cut,zero.crib,0,{}]);for(const [hand,cut,crib,total,breakdown] of cases){await page.fill('#score-hand',hand);await page.fill('#score-cut',cut);await page.locator('#score-crib').setChecked(crib);const r=await action('#hand-score-form button','/api/score');A.equal(r.total,total);for(const [k,val] of Object.entries(breakdown))A.equal(r.breakdown[k],val);A((await page.locator('#hand-score-result').innerText()).startsWith(total+' points'));}await page.fill('#score-hand','5S 5H 5D JC');await page.fill('#score-cut','5C');await page.locator('#score-crib').uncheck();await action('#hand-score-form button','/api/score');});
await check('visible pegging bench independent piles, refusals and recovery',async()=>{for(const [pile,card,count,points] of [['5S','TH',15,2],['5S 7H','6D',18,3],['5S 5H','5D',15,8],['5S TH 6H 7H AC','2S',31,2],['','AS',1,0]]){await page.fill('#score-pile',pile);await page.fill('#score-card',card);const r=await action('#play-score-form button','/api/play/score');A.equal(r.total,count);A.equal(r.points,points);if(points)A(r.why.length);A((await page.locator('#play-score-result').innerText()).includes(points+' points'));}for(const [pile,card] of [['TS TH TD','2S'],['5C','5C']]){await page.fill('#score-pile',pile);await page.fill('#score-card',card);const response=page.waitForResponse(r=>r.url().endsWith('/api/play/score'));await page.locator('#play-score-form button').click();A.equal((await response).status(),409);A(await page.locator('#play-score-result').innerText());}await page.fill('#score-pile','5S 7H');await page.fill('#score-card','6D');await action('#play-score-form button','/api/play/score');});
await check('all forty fixture totals and 960 permutations through observed server scorer',async()=>{A.equal(F.length,40);for(const f of F){const original=(await req('POST','/api/score',{hand:f.hand,cut:f.cut,crib:f.crib}));A.equal(original.status,200);A.equal(original.data.total,f.total,JSON.stringify(f));for(const hand of perms(f.hand)){const r=await req('POST','/api/score',{hand,cut:f.cut,crib:f.crib});A.equal(r.status,200);A.deepEqual(r.data,original.data);}}});
await check('invalid scoring refuses without crashing; valid recovery',async()=>{for(const body of [{hand:['ZZ','2S','3H','4D'],cut:'5C',crib:false},{hand:['AS','AS','3H','4D'],cut:'5C',crib:false},{hand:['AS','2S','3H'],cut:'5C',crib:false},{hand:[null,'2S','3H','4D'],cut:'5C',crib:false},{hand:['AS','2S','3H','4D'],crib:false}]){const r=await req('POST','/api/score',body);A(r.status>=400&&r.status<500);A(r.data.error);}A.equal((await req('POST','/api/score',{...F[0]})).data.total,29);});
await check('repeatable practice deal, hidden identities, named seats and illegal order refusal',async()=>{await create();A.equal(v.players.a.name,'Marion Ashgrove');A.deepEqual(v.you.hand,P.pegging.a);await refuse('cut',{seat:'a'});for(const s of ['a','b']){const x=await state(s),other=s==='a'?'b':'a';A.deepEqual(x.you.hand,P.pegging[s]);for(const c of P.pegging[other])A(!JSON.stringify(x).includes('"'+c+'"'));}await discard('a',P.pegging.a.slice(4));await refuse('discard',{seat:'a',cards:P.pegging.a.slice(4)});await discard('b',P.pegging.b.slice(4));A.equal(v.crib,4);A.equal(v.phase,'cut');v=await action('#cut','/api/games/'+id+'/cut');A.equal(v.cut,'QC');A.equal(v.turn,'b');await refuse('play',{seat:'a',card:'7H'});A.equal(await page.locator('#hand svg').count(),4);A.equal(await page.locator('#opponent-hand svg').count(),4);await shot('desktop-live');});
await check('real play unsorted run, count 28 refusal without mutation, thirty-one and last card',async()=>{await sequence(journey.slice(0,3));A.equal(v.count,18);A.deepEqual(v.scores,{a:0,b:3});await play('a','TH');A.equal(v.count,28);await seat('b');const before=await state();const response=page.waitForResponse(r=>r.url().endsWith('/play')&&r.request().method()==='POST');await page.locator('[data-card="9D"]').click();A.equal((await response).status(),409);await page.waitForFunction(()=>document.querySelector('#err').textContent.length>0);A.deepEqual(await state(),before);await refuse('play',{seat:'b',card:'9D'});await play('b','AC');A.equal(await page.locator('#err').innerText(),'');await play('a','2S');A.equal(v.count,0);A.deepEqual(v.scores,{a:2,b:3});await sequence(journey.slice(6));A.equal(v.phase,'show');A.deepEqual(v.scores,{a:3,b:3});});
await check('ordered complete show, revealed crib and persistent between state',async()=>{v=await action('#show','/api/games/'+id+'/show');A.deepEqual(v.shown.map(s=>[s.label,s.total]),[['non-dealer',6],['dealer',4],['crib',0]]);A.deepEqual(v.scores,{a:7,b:9});A.equal(v.phase,'between');A.equal(v.crib.length,4);A.equal(await page.locator('.show-entry').count(),3);const before=await state('b');await page.reload();await page.waitForFunction(()=>document.querySelector('#phase').textContent==='between');A.deepEqual(await state('b'),before);await shot('desktop-show');await page.setViewportSize({width:375,height:760});await noOverflow();await shot('mobile-show');await page.setViewportSize({width:1280,height:800});});
await check('same game continues, dealer alternates on hands two and three',async()=>{const old=id;v=await action('#deal','/api/games/'+id+'/deal');A.equal(v.id,old);A.equal(v.hand_no,2);A.equal(v.dealer,'b');A.deepEqual(v.scores,{a:7,b:9});for(const s of ['a','b']){const x=await state(s);A.equal(new Set(x.you.hand).size,6);await discard(s,x.you.hand.slice(4));}v=await action('#cut','/api/games/'+id+'/cut');for(let i=0;v.phase==='play'&&i<12;i++){const x=await state(v.turn);const c=x.you.remaining.find(c=>Math.min(10,'A23456789TJQK'.indexOf(c[0])+1)+v.count<=31);A(c);await play(v.turn,c);}A.equal(v.phase,'show');v=await action('#show','/api/games/'+id+'/show');const scores=v.scores;v=await action('#deal','/api/games/'+id+'/deal');A.equal(v.hand_no,3);A.equal(v.dealer,'a');A.deepEqual(v.scores,scores);});
await check('go awards one point once, resets count, other player leads',async()=>{await ready('go');await sequence([['b','TH'],['a','TS'],['b','9H']]);A.equal(v.count,0);A.equal(v.turn,'a');A.deepEqual(v.scores,{a:2,b:1});await sequence([['a','9S'],['b','8H'],['a','8S']]);A.equal(v.count,0);A.equal(v.turn,'b');A.deepEqual(v.scores,{a:5,b:1});});
await check('real pairs, royal pairs, double royal and last-card plus pair',async()=>{await ready('pairs');const expected=[{a:0,b:0},{a:2,b:0},{a:2,b:8},{a:14,b:8},{a:14,b:8},{a:16,b:8},{a:16,b:8},{a:19,b:8}];for(let i=0;i<pairs.length;i++){await play(...pairs[i]);A.deepEqual(v.scores,expected[i]);}A.equal(v.phase,'show');});
await check('show stops immediately at pone, dealer and crib winning boundaries',async()=>{for(const [a,b,winner,shown,scores] of [[0,104,'b',1,{a:19,b:121}],[93,0,'a',2,{a:121,b:18}],[89,0,'a',3,{a:121,b:18}]]){await ready('pairs',a,b);await sequence(pairs);v=await action('#show','/api/games/'+id+'/show');A.equal(v.phase,'over');A.equal(v.shown.length,shown);A.deepEqual(v.scores,scores);await refuse('show',{seat:'a'});await refuse('deal',{seat:'a'});await page.reload();await page.waitForFunction(()=>document.querySelector('#phase').textContent==='over');A.deepEqual((await state()).scores,scores);}});
await check('heels immediate score and capped win, ladder increments exactly once',async()=>{await ready('heels');A.deepEqual(v.scores,{a:2,b:0});A.equal(v.phase,'play');const before=await get('/api/ladder');await ready('heels',120,113);A.deepEqual(v.scores,{a:121,b:113});A.equal(v.phase,'over');A.equal(v.shown.length,0);const after=await get('/api/ladder');for(const m of before.members){const n=after.members.find(x=>x.no===m.no);A.equal(n.played,m.played+(['M-014','M-021'].includes(m.no)?1:0));A.equal(n.won,m.won+(m.no==='M-014'?1:0));}A.equal(after.games.filter(g=>g.id===id&&g.finished).length,1);await refuse('cut',{seat:'a'});A.deepEqual(await get('/api/ladder'),after);finished=id;await shot('desktop-win');});
await check('pegging immediate win caps at 121 and rejects further moves',async()=>{await ready('pegging',120,0);await play('b','5S');await play('a','TH');A.equal(v.phase,'over');A.deepEqual(v.scores,{a:121,b:0});await refuse('play',{seat:'b',card:'6H'});await refuse('show',{seat:'a'});});
await check('normal new game has distinct hands; fifteen at zero and wrong B turn refusal',async()=>{v=await action('#new','/api/games');id=v.id;A.deepEqual(v.scores,{a:0,b:0});const a=await state(),b=await state('b');A.equal(new Set([...a.you.hand,...b.you.hand]).size,12);await ready();await play('b','5S');await refuse('play',{seat:'b',card:'6H'});await play('a','TH');A.equal(v.count,15);A.deepEqual(v.scores,{a:2,b:0});});
await check('practice validation and scoring cannot mutate saved games or ladder',async()=>{await ready();const before=await state(),ladder=await get('/api/ladder'),games=await get('/api/games');for(const a of [-1,.5,121])A.equal((await req('POST','/api/games',{practice:'pegging',start_scores:{a,b:0}})).status,409);await action('#hand-score-form button','/api/score');await action('#play-score-form button','/api/play/score');A.deepEqual(await state(),before);A.deepEqual(await get('/api/ladder'),ladder);A.deepEqual(await get('/api/games'),games);});
await check('mobile reachability, reduced motion and labelled keyboard card controls',async()=>{await page.setViewportSize({width:375,height:760});await create();await noOverflow();const card=page.locator('#hand button').first();await card.focus();A(await card.getAttribute('aria-label'));await page.keyboard.press('Space');A.equal(await card.getAttribute('aria-pressed'),'true');A.equal(await card.evaluate(e=>getComputedStyle(e).transitionDuration),'0s');A.notEqual(await card.evaluate(e=>getComputedStyle(e).outlineStyle),'none');await shot('mobile-live');await action('#hand-score-form button','/api/score');await noOverflow();await shot('mobile-bench');await page.setViewportSize({width:1280,height:800});});
await check('pending save rejects double click while one actual request is held',async()=>{await create();let release,arrived;const held=new Promise(r=>release=r),seen=new Promise(r=>arrived=r);let count=0;await page.route('**/api/games/'+id+'/discard',async route=>{count++;arrived();await held;await route.continue();});for(const c of P.pegging.a.slice(4))await page.locator('[data-card="'+c+'"]').click();const wait=page.waitForResponse(r=>r.url().endsWith('/discard'));await page.locator('#discard').click();await seen;A.equal(await page.locator('main').getAttribute('aria-busy'),'true');A(await page.locator('#seatb').isDisabled());await page.locator('#discard').click();release();await wait;await page.waitForFunction(()=>!document.querySelector('main').hasAttribute('aria-busy'));await page.unroute('**/api/games/'+id+'/discard');A.equal(count,1);A.equal((await state()).you.discarded,true);});
await check('reload, clean browser context and saved chooser preserve partial play',async()=>{await ready();await sequence(journey.slice(0,3));const a=await state(),b=await state('b');await page.reload();await page.waitForFunction(()=>document.querySelector('#s-count').textContent==='18');A.deepEqual(await state(),a);A.deepEqual(await state('b'),b);const clean=await browser.newContext();const p=await clean.newPage();await p.goto(base);await p.waitForSelector('#saved-games option[value="'+id+'"]',{state:'attached'});await p.selectOption('#saved-games',id);await p.click('#open-game');await p.waitForFunction(()=>document.querySelector('#s-count').textContent==='18');await clean.close();});
await check('manifest contract, twice restarted SQLite state, seed once and legal continuation',async()=>{const manifest=fs.readFileSync('/app/APP_MANIFEST.md','utf8');A.match(manifest,/```bash\s+node serve\.js/);A.match(manifest,/SQLite[^\n]*\/app\/gambit\.db/);const fd=fs.openSync('/app/gambit.db','r'),header=Buffer.alloc(16);fs.readSync(fd,header,0,16,0);fs.closeSync(fd);A.equal(header.toString(),'SQLite format 3\0');const a=await state(),b=await state('b'),l=await get('/api/ladder'),f=await get('/api/games/'+finished);for(let i=0;i<2;i++){execFileSync('bash',['/tests/app-lifecycle.sh','restart'],{stdio:'pipe'});A.deepEqual(await state(),a);A.deepEqual(await state('b'),b);A.deepEqual(await get('/api/ladder'),l);A.deepEqual(await get('/api/games/'+finished),f);}await page.reload();await page.waitForFunction(()=>document.querySelector('#s-count').textContent==='18');await play('a','TH');A.equal(v.count,28);});
await check('no fatal browser errors, same-origin assets and drawn card/board surfaces',async()=>{A.deepEqual(errors,[]);A(requests.every(u=>u.startsWith(base)));A.equal(await page.locator('canvas,img').count(),0);A(await page.locator('#hand svg text').count()>0);});
fs.writeFileSync('/evidence/browser-results.json',JSON.stringify({kind:'local deterministic checks, not an LLM Oracle score',results,errors,requests:requests.length},null,2));await browser.close();})().catch(async e=>{console.error(e);if(page)await shot('failure').catch(()=>{});if(browser)await browser.close();process.exitCode=1;});
