const {chromium} = require('/usr/local/lib/node_modules/@playwright/mcp/node_modules/playwright');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  await page.goto('http://localhost:3000');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.locator('#app-view').waitFor({state:'visible'});
  await page.screenshot({path:'/evidence/baseline-dashboard.png',fullPage:true});
  await page.getByRole('button',{name:'Accounts',exact:true}).click();
  await page.getByRole('row').filter({hasText:'ACCT-C7'}).getByRole('button',{name:'Details'}).click();
  const bill=page.getByRole('button',{name:'Bill this cycle (billing operator)'});
  const response=page.waitForResponse(r=>r.url().endsWith('/bill')&&r.request().method()==='POST');
  await bill.click(); await response;
  await page.waitForTimeout(500);
  const staleBillControl=await bill.isVisible();
  await page.evaluate(async()=>{await fetch('/api/auth/logout',{method:'POST'}); await refresh();});
  const protectedDetailAfterLogout=await page.locator('#detail-backdrop').isVisible();
  const protectedShellAfterLogout=await page.locator('#app-view').isVisible();
  fs.writeFileSync('/evidence/baseline-results.json',JSON.stringify({staleBillControl,protectedDetailAfterLogout,protectedShellAfterLogout,errors},null,2));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
