const assert=require('node:assert/strict'),fs=require('node:fs'),{randomUUID}=require('node:crypto');
const {chromium}=require('/usr/local/lib/node_modules/@playwright/mcp/node_modules/playwright');
const results=[],observations=[],base='http://127.0.0.1:3000';let browser,ada,ben,page,z;
async function check(name,fn){await fn();results.push({name,passed:true});console.log('PASS '+name);}
async function api(path,t,body,method){const r=await fetch(base+path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',Connection:'close',...(t?{Authorization:'Bearer '+t}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert(r.ok,JSON.stringify(data));return data;}
async function login(name){return (await api('/api/auth/login',null,{email:name+'@coursemark.example',password:'Coursemark!2026'})).token;}
async function write(path,t,body={}){return api(path,t,{...body,expected_revision:(await api('/api/me',t)).revision,operation_id:randomUUID()});}
async function action(selector,path){const waiting=page.waitForResponse(r=>r.url().endsWith(path)&&r.request().method()!=='GET');await page.locator(selector).click();const r=await waiting;await r.finished();assert(r.ok(),await r.text());}
async function exception(student,assessment,excused){await page.locator('#edit-exception').click();const f=page.locator('#exception-form');await f.locator('[name=student_id]').selectOption(student);await f.locator('[name=assessment_id]').selectOption(assessment);await f.locator('[name=excused]').selectOption(String(excused));await f.locator('[name=reason]').fill('Recorded exception for outcome review');await action('#exception-form button[type=submit]','/api/outcome-exceptions');await page.locator('#exception-dialog').waitFor({state:'hidden'});}
async function final(student,value){const r=(await api('/api/outcomes',ada)).rows.find(r=>r.student.id===student);assert.equal(r.final_percentage,value);observations.push({student,expected:value,observed:r.final_percentage});fs.writeFileSync('/evidence/outcome-ui-observations.json',JSON.stringify(observations,null,2));return r;}
(async()=>{
 ada=await login('ada.mensah');ben=await login('ben.okafor');
 const a=await write('/api/assessments',ada,{course_id:'BIO-214',title:'UI arithmetic zero',opens_at:'2026-09-02T11:00:00Z',due_at:'2026-09-02T13:00:00Z',duration_minutes:30,max_attempts:1});z=a.assessment.id;await write('/api/assessments/'+z+'/items',ada,{kind:'multiple_choice',prompt:'Choose Oak',points:5,options:['Oak','Pine'],answer:'Oak'});await write('/api/assessments/'+z+'/publish',ada);const at=await write('/api/assessments/'+z+'/start',ben);await write('/api/attempts/'+at.attempt.id+'/submit',ben);await write('/api/attempts/'+at.attempt.id+'/release',ada);
 browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});page=await browser.newPage();await page.goto(base);await page.locator('#login-email').fill('ada.mensah@coursemark.example');await page.locator('#login-password').fill('Coursemark!2026');await page.locator('#login-form button[type=submit]').click();await page.locator('#app-view').waitFor({state:'visible'});await page.locator('.tab[data-view=gradebook]').click();await page.locator('#open-outcomes').click();
 await check('actual Oracle artifact completes long-policy and all excuse/restore arithmetic through UI',async()=>{
  await page.locator('#edit-weights').click();const fields=page.locator('#weight-rows input');const count=await fields.count();assert(count>5);for(let i=0;i<count;i++){const field=fields.nth(i),id=await field.getAttribute('data-weight');await field.fill(id==='A-03'||id===z?'50':'0');}await action('#weight-form button[type=submit]','/api/outcome-weights');await page.locator('#weight-dialog').waitFor({state:'hidden'});await final('user_4',22.5);await final('user_3',null);
  await exception('user_4',z,true);await final('user_4',45);await exception('user_4',z,false);await final('user_4',22.5);await exception('user_3',z,true);await final('user_3',50);await exception('user_3','A-03',true);await final('user_3',null);await exception('user_3','A-03',false);await final('user_3',50);
  await page.locator('#outcome-search').fill('ben.okafor');assert.equal(await page.locator('.outcome-person').count(),1);assert.match(await page.locator('.outcome-person').innerText(),/22.50%/);await page.locator('#outcome-search').fill('not-a-student');assert.match(await page.locator('#outcome-rows').innerText(),/No matching student/);await page.locator('#outcome-search').fill('');await page.waitForFunction(()=>document.querySelectorAll('.outcome-person').length===2);assert.equal(await page.locator('.outcome-person').count(),2);await page.screenshot({path:'/evidence/oracle-working-outcomes.png',fullPage:true,animations:'disabled'});
 });
 await check('handoff worksheet and reviewed batch remain reachable after full outcome journey',async()=>{
  await page.keyboard.press('Escape');await page.locator('#outcome-dialog').waitFor({state:'hidden'});const row=page.locator('#gradebook-list .panel').filter({hasText:'Review practice'});assert.equal(await row.locator('[data-worksheet]').count(),1);await row.locator('[data-worksheet]').click();await page.locator('#worksheet-dialog').waitFor({state:'visible'});await page.screenshot({path:'/evidence/oracle-working-worksheet.png',fullPage:true,animations:'disabled'});await page.keyboard.press('Escape');await page.locator('#worksheet-dialog').waitFor({state:'hidden'});await page.locator('#open-release-batch').click();const candidate=page.locator('#release-selection label').filter({hasText:'Review practice'});await candidate.locator('input').check();await action('#preview-release','/api/release-plans');await page.locator('#release-preview').filter({hasText:'Review practice'}).waitFor();assert(await page.locator('#commit-release').isEnabled());await page.screenshot({path:'/evidence/oracle-working-release-preview.png',fullPage:true,animations:'disabled'});
 });
 await browser.close();fs.writeFileSync('/evidence/outcome-ui.json',JSON.stringify({kind:'Supplementary local checks of exported Oracle implementation; not platform grades',results},null,2));
})().catch(async error=>{console.error(error);if(page){await page.screenshot({path:'/evidence/outcome-ui-failure.png',fullPage:true}).catch(()=>{});fs.writeFileSync('/evidence/outcome-ui-failure.html',await page.content());}results.push({passed:false,error:String(error),stack:error.stack});fs.writeFileSync('/evidence/outcome-ui.json',JSON.stringify({results},null,2));if(browser)await browser.close();process.exitCode=1;});
