const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('/usr/local/lib/node_modules/@playwright/mcp/node_modules/playwright');
const seed=JSON.parse(fs.readFileSync('/solution/app/seed_data.json','utf8'));
const conditional=process.env.CONDITIONAL_ONLY==='1';
const out=conditional?'/work/conditional':'/work/commerce';fs.mkdirSync(out,{recursive:true});
const report={scope:'Fresh final-golden browser commerce observations; no paid judge',conditionalOnly:conditional,checks:[],requests:[],pageErrors:[],started_at:new Date().toISOString()};
let browser,page;const money=n=>(n/100).toFixed(2),title=sku=>seed.variants.find(v=>v.sku===sku).title;
const lines=(...triples)=>triples.map(([sku,size,qty])=>({sku,size,qty}));
const variant=(sku,size)=>seed.variants.find(v=>v.sku===sku&&v.size===size);
async function direct(url,body){const value=await page.evaluate(async({url,body})=>{const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,body:await r.json()}},{url,body});report.requests.push({url,request:body,...value});return value;}
async function stocks(){const data=(await direct('/api/prints')).body;return Object.fromEntries(data.prints.flatMap(p=>p.sizes.map(v=>[p.sku+':'+v.size,v.in_stock])));}
const order=async ref=>(await direct('/api/orders/'+ref)).body;
function expected(entries){let gross=0,saving=0,grams=0;const combined={};for(const x of entries)combined[x.sku+':'+x.size]=(combined[x.sku+':'+x.size]||0)+x.qty;for(const[key,q]of Object.entries(combined)){const[sku,size]=key.split(':'),v=variant(sku,size);gross+=v.price_pence*q;saving+=(v.price_pence-(q>=v.tier_qty?v.tier_price_pence:v.price_pence))*q;grams+=seed.size_weights.find(v=>v.size===size).grams*q;}const band=seed.postage_bands.filter(b=>b.up_to_grams>0).sort((a,b)=>a.up_to_grams-b.up_to_grams).find(b=>grams<=b.up_to_grams);const postage=entries.length?(band?.price_pence||0):0;return[gross,saving,postage,gross-saving+postage];}
async function summary(values){await page.waitForFunction(values=>{const numbers=[...document.querySelectorAll('.summary dd')].map(e=>Number(e.textContent.replace(/[^0-9.]/g,'')));return JSON.stringify(numbers)===JSON.stringify(values.map(v=>v/100));},values,{timeout:8000});}
async function grid(){await page.getByRole('button',{name:'The prints',exact:true}).click();await page.locator('.print-card').first().waitFor();}
async function clear(){await page.getByRole('button',{name:/Open basket,/}).click();while(await page.getByRole('button',{name:/^Remove /}).count())await page.getByRole('button',{name:/^Remove /}).first().click();assert.equal(await page.locator('.basket-line').count(),0);}
async function add(sku,size,qty){await grid();await page.getByRole('button',{name:'View '+title(sku),exact:true}).click();await page.getByRole('button',{name:new RegExp('^'+size)}).click();const q=page.getByRole('spinbutton',{name:'Quantity for '+title(sku)+' '+size+' to add',exact:true});await q.fill(String(qty));await q.blur();await page.getByRole('button',{name:'Add to basket',exact:true}).click();await page.getByRole('status').filter({hasText:'added to your basket'}).waitFor();}
async function basket(entries){await clear();for(const r of entries)await add(r.sku,r.size,r.qty);await page.getByRole('button',{name:/Open basket,/}).click();await summary(expected(entries));}
async function buy(entries,label){await basket(entries);const figures=expected(entries);await page.getByRole('button',{name:'Continue to checkout',exact:true}).click();const name='Crosscheck '+label+' '+Date.now();for(const[key,value]of[['Full name',name],['Address line 1','18 Ink Lane'],['Town or city','Bristol'],['Postcode','BS1 4QA']])await page.getByLabel(key,{exact:true}).fill(value);await page.getByRole('button',{name:'Review order',exact:true}).click();await summary(figures);assert((await page.locator('address').innerText()).includes(name));const wait=page.waitForResponse(r=>r.url().endsWith('/api/orders')&&r.request().method()==='POST');await page.getByRole('button',{name:'Place order',exact:true}).click();const r=await wait;assert.equal(r.status(),201);const saved=await r.json(),request=r.request().postDataJSON();report.requests.push({purpose:'ordinary UI positive purchase',url:r.url(),request,status:r.status(),body:saved});await page.getByText(saved.reference,{exact:true}).waitFor();await summary(figures);assert.deepEqual([saved.subtotal_pence,saved.trade_saving_pence,saved.postage_pence,saved.total_pence],figures);assert.equal(saved.address_name,name);assert.deepEqual(await order(saved.reference),saved);return{saved,request};}
async function refusal(body){const before=await stocks(),r=await direct('/api/orders',body);assert(r.status>=400&&r.status<500);assert(!r.body.reference);assert.deepEqual(await stocks(),before);return r;}
function fresh(body,changes={}){return{...structuredClone(body),checkout_id:crypto.randomUUID(),...changes};}
async function check(id,fn){report.checks.push({id,passed:true,...await fn()});console.log('PASS '+id);}
async function cheapestSoldOut(setup){const before=await stocks();assert(before['RP-104:A2']>0);let setupReference=null;if(before['RP-104:A3']>0){assert(setup);const own=await buy(lines(['RP-104','A3',before['RP-104:A3']]),'Cheapest own setup');setupReference=own.saved.reference;}assert.equal((await stocks())['RP-104:A3'],0);for(let i=0;i<2;i++){if(i===0)await grid();else{await page.reload();await page.locator('.print-card').first().waitFor();}const card=page.locator('.print-card').filter({has:page.getByRole('button',{name:'View Slack Water',exact:true})});assert.match(await card.innerText(),/37\.95/);assert.match(await card.locator('.availability').innerText(),/In stock/);}assert.equal((await stocks())['RP-104:A2'],before['RP-104:A2']);await page.getByRole('button',{name:'View Slack Water',exact:true}).click();await page.getByRole('button',{name:/^A3/}).click();assert.match(await page.getByRole('button',{name:/^A3/}).innerText(),/Sold out/);await page.getByRole('button',{name:/^A2/}).click();assert.match(await page.getByRole('button',{name:/^A2/}).innerText(),/56\.50/);assert(await page.getByRole('button',{name:'Add to basket',exact:true}).isEnabled());await page.screenshot({path:out+'/cheapest-sold-out-detail.png',fullPage:true});return{before,setupReference,gridRegularPrice:3795,retainedA2Stock:before['RP-104:A2'],afterReload:true};}
async function main(){browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium'});report.chromium=browser.version();page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.pageErrors.push(e.message));await page.goto('http://localhost:3000');await page.locator('.print-card').first().waitFor();
 if(conditional){await check('cheapest_sold_out_independent_setup',()=>cheapestSoldOut(true));report.passed=true;return;}
 await check('all_catalogue_variant_details',async()=>{const current=await stocks();for(const sku of [...new Set(seed.variants.map(x=>x.sku))]){await grid();const card=page.locator('.print-card').filter({has:page.getByRole('button',{name:'View '+title(sku),exact:true})});const cardImage=await card.locator('img').boundingBox();const variants=seed.variants.filter(v=>v.sku===sku);assert((await card.innerText()).includes(money(Math.min(...variants.map(x=>x.price_pence)))));await page.getByRole('button',{name:'View '+title(sku),exact:true}).click();const detailImage=await page.locator('.product-art img').boundingBox();assert(detailImage.width>cardImage.width);assert(await page.locator('.product-art img').evaluate(e=>e.complete&&e.naturalWidth>0));for(const v of variants){const control=page.getByRole('button',{name:new RegExp('^'+v.size)});await control.click();assert((await control.innerText()).includes(money(v.price_pence)));assert((await page.locator('.paper-spec').innerText()).includes(v.stock_sheet));assert((await page.locator('.trade-note').innerText()).includes(v.tier_qty+'+'));assert((await page.locator('.trade-note').innerText()).includes(money(v.tier_price_pence)));assert((await page.locator('.product-buy .availability').innerText()).includes(current[sku+':'+v.size]===0?'Sold out':current[sku+':'+v.size]+' available'));}}return{prints:8,variants:13,currentStocks:current};});
 await check('variant_stock_ui_and_zero_quantity',async()=>{await add('RP-102','A3',1);await page.getByRole('button',{name:/^A2/}).click();assert(await page.getByRole('button',{name:'Sold out',exact:true}).isDisabled());await clear();await add('RP-104','A2',1);await page.getByRole('button',{name:/Open basket,/}).click();await page.getByRole('button',{name:'Increase Slack Water A2',exact:true}).click();await page.getByRole('alert').filter({hasText:'Only 1'}).waitFor();assert.equal(await page.getByRole('spinbutton',{name:'Quantity for Slack Water A2',exact:true}).inputValue(),'1');await clear();await basket(lines(['RP-108','A2',1]));const q=page.getByRole('spinbutton',{name:'Quantity for Night Ferry A2',exact:true});await q.fill('0');await q.blur();await page.reload();await page.getByText('Your basket is empty.',{exact:false}).waitFor();return{excessPreservesOne:true,zeroRemovesAcrossReload:true};});
 await check('trade_reversal_and_postage_boundaries_ui',async()=>{for(const entries of[lines(['RP-108','A3',4],['RP-108','A2',1]),lines(['RP-108','A3',5],['RP-108','A2',1]),lines(['RP-108','A3',4],['RP-108','A2',1]),lines(['RP-103','A3',1]),lines(['RP-103','A3',2],['RP-101','A2',2]),lines(['RP-103','A3',8],['RP-101','A2',4],['RP-108','A2',4]),lines(['RP-103','A3',9],['RP-101','A2',4],['RP-108','A2',4])]){await basket(entries);}assert.match(await page.locator('.summary').innerText(),/Collection only/);await clear();return{exactTotalsCheckedBeforeAnyOrders:true,bandWeights:[90,500,2000,2090]};});
 let historical;
 await check('historical_and_unknown_reference_ui',async()=>{await page.getByRole('button',{name:'Track an order',exact:true}).click();await page.getByLabel('Order reference',{exact:true}).fill('RP-100001');await page.getByRole('button',{name:'Find order',exact:true}).click();await page.getByText('RP-100001',{exact:true}).waitFor();historical=await order('RP-100001');assert.equal(historical.status,'dispatched');await summary([7000,0,320,7320]);assert.match(await page.locator('.receipt-lines').innerText(),/35\.00/);await page.getByRole('button',{name:'Track an order',exact:true}).click();await page.getByLabel('Order reference',{exact:true}).fill('RP-999999');await page.getByRole('button',{name:'Find order',exact:true}).click();await page.getByRole('heading',{name:'Order not found',exact:true}).waitFor();assert.equal(await page.locator('.receipt-lines').count(),0);const freshOrder=await buy(lines(['RP-101','A3',1]),'Historical current control');assert.equal(freshOrder.saved.total_pence,3970);assert.deepEqual(await order('RP-100001'),historical);return{newReference:freshOrder.saved.reference,historicalUnchanged:true};});
 await check('mixed_variant_trade_order',async()=>{const before=await stocks();const p=await buy(lines(['RP-101','A3',2],['RP-105','A3',1],['RP-106','A3',5]),'Mixed trade');assert.equal(p.saved.total_pence,30005);const after=await stocks();for(const r of p.request.lines)assert.equal(after[r.sku+':'+r.size],before[r.sku+':'+r.size]-r.qty);await page.reload();await page.getByText(p.saved.reference,{exact:true}).waitFor();await summary([32635,3125,495,30005]);return{reference:p.saved.reference,storedAddressAndPrices:true};});
 await check('fresh_checkout_ignores_forged_prices',async()=>{const p=await buy(lines(['RP-106','A2',1]),'Pricing control');const forged=fresh(p.request,{total_pence:1,postage_pence:0,unit_price_pence:1});forged.lines[0].unit_price_pence=1;const before=await stocks();const r=await direct('/api/orders',forged);if(r.status===201){assert.deepEqual([r.body.subtotal_pence,r.body.postage_pence,r.body.total_pence],[6450,320,6770]);assert.equal((await stocks())['RP-106:A2'],before['RP-106:A2']-1);assert.deepEqual(await order(r.body.reference),r.body);}else{assert(r.status>=400);assert.deepEqual(await stocks(),before);}assert.deepEqual(await order(p.saved.reference),p.saved);return{status:r.status,authoritativeTotal:6770};});
 await check('combined_lines_and_invalid_checkout_atomicity',async()=>{const c=await buy(lines(['RP-103','A3',1]),'Quantity control');await basket(lines(['RP-103','A3',3]));await add('RP-103','A3',2);await page.getByRole('button',{name:/Open basket,/}).click();await summary([21250,3125,320,18445]);assert.equal(await page.locator('.basket-line').count(),1);const combined=await direct('/api/orders',fresh(c.request,{lines:lines(['RP-103','A3',3],['RP-103','A3',2])}));assert.equal(combined.status,201);assert.equal(combined.body.lines.length,1);assert.equal(combined.body.lines[0].qty,5);assert.equal(combined.body.total_pence,18445);assert.equal((await stocks())['RP-103:A3'],14);await clear();await refusal(fresh(c.request,{lines:lines(['RP-103','A3',8],['RP-103','A3',7])}));for(const q of[0,-1,1.5])await refusal(fresh(c.request,{lines:lines(['RP-103','A3',q])}));await refusal(fresh(c.request,{lines:lines(['RP-103','A3',1],['RP-999','A3',1])}));assert.deepEqual(await order(c.saved.reference),c.saved);assert.deepEqual(await order(combined.body.reference),combined.body);return{combinedQty:5,remaining:14,invalidCases:5};});
 await check('stale_multiline_checkout_atomicity',async()=>{const before=await stocks();await basket(lines(['RP-102','A3',2],['RP-101','A3',1]));const b=await buy(lines(['RP-102','A3',8]),'Stale competitor');assert.equal(b.saved.total_pence,27815);const stale=fresh(b.request,{lines:lines(['RP-102','A3',2],['RP-101','A3',1])});await refusal(stale);const after=await stocks();assert.equal(after['RP-102:A3'],1);assert.equal(after['RP-101:A3'],before['RP-101:A3']);assert.deepEqual(await order(b.saved.reference),b.saved);return{competitor:b.saved.reference,validCompanionUnchanged:true};});
 await check('checkout_identity_replay_and_new_purchase',async()=>{const a=await buy(lines(['RP-108','A2',1]),'Retry');const before=await stocks();for(let i=0;i<2;i++){const replay=await direct('/api/orders',a.request);assert.equal(replay.status,200);assert.deepEqual(replay.body,a.saved);assert.deepEqual(await stocks(),before);}const changed=structuredClone(a.request);changed.lines[0].qty=2;await refusal(changed);const address=structuredClone(a.request);address.address.line1='99 A Different Street';await refusal(address);const b=await buy(lines(['RP-108','A2',1]),'Retry new purchase');assert.notEqual(a.saved.reference,b.saved.reference);assert.equal((await stocks())['RP-108:A2'],2);assert.deepEqual(await order(a.saved.reference),a.saved);return{first:a.saved.reference,second:b.saved.reference,replays:2,changedPayloadsRefused:2};});
 await check('cancellation_terminal_and_dispatched_refusal',async()=>{const p=await buy(lines(['RP-108','A3',5]),'Cancellation');assert.equal(p.saved.total_pence,18445);await page.getByRole('button',{name:'Cancel order',exact:true}).click();await page.getByRole('button',{name:'Confirm cancellation',exact:true}).click();await page.getByRole('heading',{name:'Order cancelled.',exact:true}).waitFor();const cancelled=await order(p.saved.reference);assert.equal(cancelled.status,'cancelled');for(const key of['lines','address_name','address_line1','address_city','address_postcode','subtotal_pence','trade_saving_pence','postage_pence','total_pence'])assert.deepEqual(cancelled[key],p.saved[key]);assert.equal((await stocks())['RP-108:A3'],6);for(let i=0;i<2;i++){const r=await direct('/api/orders/'+p.saved.reference+'/cancel',{});assert.deepEqual(r.body,cancelled);assert.equal((await stocks())['RP-108:A3'],6);}const replay=await direct('/api/orders',p.request);assert.deepEqual(replay.body,cancelled);const before=await stocks(),dispatched=await direct('/api/orders/RP-100001/cancel',{});assert(dispatched.status>=400);assert.deepEqual(await stocks(),before);assert.deepEqual(await order('RP-100001'),historical);return{cancelledReference:p.saved.reference,repeatedRestorePrevented:true,dispatchedUnchanged:true};});
 await check('simultaneous_last_copy_and_cheapest_sold_out',async()=>{const p=await buy(lines(['RP-104','A3',1]),'Race control');const requests=[fresh(p.request),fresh(p.request)];const raced=await page.evaluate(async bodies=>Promise.all(bodies.map(async body=>{const r=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,body:await r.json()}})),requests);report.requests.push({purpose:'concurrent independent attempts',requests,results:raced});assert.equal(raced.filter(x=>x.status===201).length,1);assert.equal(raced.filter(x=>x.status>=400).length,1);assert.equal((await stocks())['RP-104:A3'],0);const winner=raced.find(x=>x.status===201);assert.equal(winner.body.total_pence,3970);assert.deepEqual(await order(p.saved.reference),p.saved);assert.deepEqual(await order(winner.body.reference),winner.body);const cheapest=await cheapestSoldOut(false);return{winner:winner.body.reference,cheapest};});
 await check('last_A2_then_fresh_oversell_refusal',async()=>{const p=await buy(lines(['RP-104','A2',1]),'Last A2');assert.equal(p.saved.total_pence,5970);assert.equal((await stocks())['RP-104:A2'],0);await refusal(fresh(p.request));assert.deepEqual(await order(p.saved.reference),p.saved);return{reference:p.saved.reference,lastUnitAccepted:true};});
 await check('successive_orders_keep_independent_tiers',async()=>{const a=await buy(lines(['RP-101','A2',2]),'Successive regular');assert.equal(a.saved.total_pence,11620);assert.equal((await stocks())['RP-101:A2'],3);const b=await buy(lines(['RP-101','A2',3]),'Successive trade');assert.equal(b.saved.total_pence,15545);assert.equal((await stocks())['RP-101:A2'],0);assert.deepEqual(await order(a.saved.reference),a.saved);assert.deepEqual(await order(b.saved.reference),b.saved);return{regularReference:a.saved.reference,tradeReference:b.saved.reference};});
 assert.deepEqual(report.pageErrors,[]);report.finalStock=await stocks();report.passed=true;
}
main().catch(async e=>{report.passed=false;report.error=e.stack;console.error(e);if(page)await page.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});process.exitCode=1}).finally(async()=>{report.finished_at=new Date().toISOString();fs.writeFileSync(out+'/results.json',JSON.stringify(report,null,2));if(browser)await browser.close()});
