'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../../../..'),base=__dirname;
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const read=file=>JSON.parse(fs.readFileSync(file));
const rel=file=>path.relative(root,file).replaceAll('\\','/');
const ref=(file,pointer)=>({path:rel(file),sha256:hash(fs.readFileSync(file)),...(pointer?{json_pointer:pointer}:{})});
const write=(name,value)=>{const file=path.join(base,name);assert(!fs.existsSync(file),'Do not overwrite indexed evidence: '+name);fs.writeFileSync(file,typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');return ref(file);};
function files(dir){const found={};function scan(current,prefix=''){for(const ent of fs.readdirSync(current,{withFileTypes:true})){const name=prefix+ent.name,file=path.join(current,ent.name);if(ent.isDirectory())scan(file,name+'/');else found[name]=hash(fs.readFileSync(file));}}scan(dir);return found;}
const releaseDir=path.join(base,'../review-candidate'),releaseFile=path.join(releaseDir,'candidate_manifest.json'),release=read(releaseFile);
const archiveFile=path.join(releaseDir,release.archive);assert.equal(hash(fs.readFileSync(archiveFile)),'f86708344b0861aad8a48049996c7b72266c29d6d68bf377358a0c5810aad6ae');assert.equal(release.sha256,hash(fs.readFileSync(archiveFile)));
const executionFile=path.join(base,'frozen_inputs.json'),finalFile=path.join(base,'frozen_final_release_inputs.json'),execution=read(executionFile),final=read(finalFile);
for(const key of ['functional_sha256','prompt_sha256','context_sha256','solution_files'])assert.deepEqual(execution[key],final[key],'Execution/final drift: '+key);
const taskFiles=files(path.join(base,'task-snapshot'));assert.equal(Object.keys(taskFiles).length,50);assert.deepEqual(taskFiles,release.source_sha256,'Execution snapshot differs from final archived task');
const cases={golden:'run-golden-20260927-181640','css-live-context-leaks':'run-css-live-context-leaks-20260927-181641','conflict-ui-clears':'run-conflict-ui-clears-20260927-181641','js-only-importer':'run-js-only-importer-20260927-181642'};
const runs={};for(const[name,dir]of Object.entries(cases)){const file=path.join(base,dir,'RESULTS.json'),r=read(file);assert.equal(r.expected_behavior_observed,true,name);assert.equal(r.node_returncode,0,name);assert.equal(r.browser.expected_behavior_observed,true,name);assert.equal(r.manifest_sha256,hash(fs.readFileSync(executionFile)));runs[name]={report:r,file,ref:ref(file),browser_ref:ref(path.join(base,dir,'browser-results.json'))};}
for(const[relative,digest]of Object.entries(final.solution_files)){if(relative.startsWith('app/'))assert.equal(runs.golden.report.app_files[relative.slice(4)],digest,'Golden runtime file mismatch '+relative);}
const baseline=read(path.join(root,'deliverables/colderwater-playground-devtools/positive-controls-fix-2026-09-27/golden/frozen_final_release_inputs.json'));assert.deepEqual(final.solution_files,baseline.solution_files,'Golden source changed from prior663e');
const golden=runs.golden.report.browser,leaks=runs['css-live-context-leaks'].report.browser,conflicts=runs['conflict-ui-clears'].report.browser,imports=runs['js-only-importer'].report.browser;
assert(golden.stale_editors.operations.every(row=>row.product_pass&&row.expectations_matched));
assert(conflicts.stale_editors.operations.every(row=>row.expected_defect_observed&&row.facts.server_unchanged&&row.facts.current_operation_recovers));
assert(imports.observations[0].items.filter(row=>row.extension===row.extension.toUpperCase()).every(row=>row.save_layer_pass));
const definitions=[
 ['cw_css_global_freshness','/browser/observations/0','Author-assigned oldGlobal was directly observed before CSS, then undefined in the matched fresh current CSS frame before any later JS Run.'],
 ['cw_css_pending_timer_cancelled','/browser/observations/1','The same4s timer fired once in DOM/log, then a second pending instance was superseded by CSS; no fired2 DOM/log/success through5.23s; fresh ordinary execution recovered.'],
 ['cw_stale_rename_refusal','/browser/stale_editors/operations/0','Actual current Rename before/after, stale real B request409, exact newer full record/list preserved independently of dirty fields.'],
 ['cw_stale_rename_draft_recovery','/browser/stale_editors/operations/0','Real older B editor retained exact dirty title/filename/source with new conflict feedback, deliberately loaded latest and reapplied/saved/reloaded exact intended fields.'],
 ['cw_stale_delete_refusal','/browser/stale_editors/operations/1','Actual current Delete before/after, stale real B request409, exact newer full record/list preserved independently of dirty fields.'],
 ['cw_stale_delete_draft_recovery','/browser/stale_editors/operations/1','Real older B editor retained exact dirty title/filename/source with new conflict feedback, deliberately loaded latest and reapplied/saved/reloaded exact intended fields.'],
 ['cw_supported_file_import','/browser/observations/2','Actual lowercase.js/.html/.css file input, exact editable imported source, own-language edit, UI Save and library reload of each exact saved identity.'],
 ['cw_import_extension_case','/browser/observations/2','Actual importer accepted.JS/.HTML/.CSS with exact filename/source.'],
 ['cw_saved_filename_extension_case','/browser/observations/2','UI current writes accepted and reloaded.JS/.HTML/.CSS filenames unchanged; independent ordinary-draft fallback also succeeded for HTML/CSS in JS-only importer mutant.'],
];
const targetMap={scope:'Nine current Functional outcomes supported by focused fresh browser facts; no full93-row or Oracle claim',archive_sha256:release.sha256,functional_sha256:final.functional_sha256,prompt_sha256:final.prompt_sha256,criterion_hash_definition:'source_block_sha256 binds each exact TOML criterion block; it is not a canonical object hash.',current_criteria:definitions.map(([id,pointer,observed])=>{const c=final.criteria.find(row=>row.id===id);assert(c,'Current criterion missing '+id);return{...c,status:'Fresh local observations complete',oracle_verdict:false,observed,evidence:[ref(runs.golden.file,pointer)]};})};
const mapRef=write('FOCUSED_CRITERION_MAP.json',targetMap);
const mutators=read(path.join(base,'variants/variant_binding.json'));
const summary={schema_version:1,created_at:new Date().toISOString(),scope:'Focused C1/C2/C3 coverage repair proof against frozen f867 archive, direct pinned Playwright. Four fresh runs, no reused row verdicts.',archive:ref(archiveFile),candidate_manifest:ref(releaseFile),execution_inputs:ref(executionFile),final_inputs:ref(finalFile),all50_execution_task_files_match_final_archive:true,solution_file_count:23,golden_source_unchanged_from_663e:true,golden_source_repairs:[],network:'none',provider_or_platform_calls:0,oracle_score_claimed:false,full93_functional_run_claimed:false,actual_mcp_tool_dispatch:false,browser_automation:'Direct Playwright package from pinned verifier image; Chromium152',verifier_image:'sha256:43757904510bf933d70d209e77077ad0173deb345f61a1477eb106f4e2380f6f',all_four_expected_outcomes_observed:true,focused_current_outcomes:9,criterion_map:mapRef,
golden:{evidence:runs.golden.ref,wall_seconds:runs.golden.report.wall_seconds,css_global:{positive_value:golden.observations[0].before.global.value,during_css_type:golden.observations[0].during_css.global.type,old_frame_detached:golden.observations[0].during_css.previous_frame_detached,new_frame_identity:!golden.observations[0].during_css.same_browser_frame_identity},css_timer:{positive_callback_dom_and_log:true,second_timer_pending_observed:true,css_run_after_second_click_ms:golden.observations[1].css_run.action_at_ms-golden.observations[1].queued_at_ms,observation_after_second_click_ms:golden.observations[1].after.observed_at_ms-golden.observations[1].queued_at_ms,fresh_second_callback_count:golden.observations[1].after.fired_count,recovery_pass:golden.observations[1].recovery_pass},stale_editor_operations:golden.stale_editors.operations.map(row=>({operation:row.operation,facts:row.facts})),imports:golden.observations[2].items.map(row=>({extension:row.extension,import_exact:row.import_exact,edit_exact:row.edit_exact,save_exact:row.save_exact,load_exact:row.load_exact}))},
mutants:[{name:'css-live-context-leaks',evidence:runs['css-live-context-leaks'].ref,observed:'Current CSS retained do-not-carry in the same live frame; the proven old timer produced fired2 DOM/log after CSS. Intended CSS styles/content and ordinary execution recovery still worked.',defects_observed:['CSS authored-global retention','CSS pending old-timer leakage'],coupling_note:'One deliberate live-context mutant retains globals/timers/handlers; this run directly inspects globals and timer effects, not an isolated single-global or single-timer implementation.'},{name:'conflict-ui-clears',evidence:runs['conflict-ui-clears'].ref,observed:'Both real stale Rename/Delete actions kept useful conflict feedback and newer server records unchanged, but cleared title/filename/source. Latest-load/reapply/current-operation recovery still succeeded.',defects_observed:['Stale Rename UI draft loss','Stale Delete UI draft loss'],independent_server_outcomes_still_pass:true},{name:'js-only-importer',evidence:runs['js-only-importer'].ref,observed:'JS and.JS imports/edit/save/load succeeded; html/css/HTML/CSS imports were refused. Independent uppercaseHTML/CSS ordinary-draft Save/reload succeeded despite import refusal.',defects_observed:['Missing lowercaseHTML/CSS import support','Missing uppercaseHTML/CSS import support'],uppercase_server_layer_still_pass:true}],
runtime_cases:Object.fromEntries(Object.entries(runs).map(([name,run])=>[name,{results:run.ref,browser_results:run.browser_ref,wall_seconds:run.report.wall_seconds,expected_behavior_observed:true}])),variant_binding:ref(path.join(base,'variants/variant_binding.json')),
limits:['This is a focused fresh proof for9 outcomes, not a new complete93-outcome run or full Oracle verdict.','Wall times are browser/container automation only; provider/LLM overhead and the150-minute full judge fit were not measured.','CSS state observation here exercised the real native-frame golden path. Virtual/worker context matching and the named unavailable-observation branch were not exercised.','Conflict tests exercised actual requests with server refusals. Proactive dirty-work prevention alternative was not required or exercised.','The import no-execution fields are incidental immediate snapshots only; this proof does not newly judge the separate2-second off-state/manual-execution outcome.','All3mutants are owned disposable copies; no shipped golden files changed.'],cleanup:{owned_containers:'All4used --rm and have exited; docker ps name=cw-coverage- returned none.',preview3420:'colderwater-golden-preview-20260927 remained running at127.0.0.1:3420->3000.'}};
const summaryRef=write('FOCUSED_PROOF_SUMMARY.json',summary);
const binding={archive:ref(archiveFile),candidate_manifest:ref(releaseFile),solution_files:final.solution_files,execution_task_files:taskFiles,execution_task_snapshot_path:rel(path.join(base,'task-snapshot')),final_inputs:ref(finalFile),execution_inputs:ref(executionFile),focused_summary:summaryRef,criterion_map:mapRef,fresh_proofs:Object.fromEntries(Object.entries(runs).map(([name,run])=>[name,run.ref])),reused_source_scoped_proofs:[],source_reuse_note:'The23golden files match663e; current9-target proof facts are fresh. No earlier row verdict is inherited here.',paid_calls:false};
const bindingRef=write('golden_evidence_binding.json',binding);
write('FOCUSED_PROOF_REPORT.md',`# Focused coverage proof\n\nCandidate ZIP: \`${release.sha256}\`. All50task files in the execution snapshot match the final archive; all23golden files match the prior663e release. No golden code repair was needed.\n\nThe fresh golden run passed all requested C1/C2/C3 observations in${summary.golden.wall_seconds.toFixed(2)}seconds. The CSS global was directly observed before CSS and absent in its matched fresh current frame. A4-second timer actually fired once; the next pending timer was replaced by CSS after${summary.golden.css_timer.css_run_after_second_click_ms.toFixed(1)}ms and remained absent for${(summary.golden.css_timer.observation_after_second_click_ms/1000).toFixed(2)}seconds. Both real two-editor stale operations retained exact dirty fields and recovered. All lowercase/uppercase JS,HTML,CSS files passed actual import/edit/Save/reload.\n\nThe3controlled mutants were detected: CSS live-context leakage; dirty-field loss despite correct server refusal; and JS-only importing despite working uppercase Save. This demonstrates separate observed facts rather than inherited verdicts.\n\nNine current outcome mappings are in[FOCUSED_CRITERION_MAP.json](FOCUSED_CRITERION_MAP.json); raw facts and timing are in[FOCUSED_PROOF_SUMMARY.json](FOCUSED_PROOF_SUMMARY.json). File hashes and source binding are in[golden_evidence_binding.json](golden_evidence_binding.json).\n\nThis was direct pinned Playwright with network disabled, not an actualMCP tool-dispatch run, provider call, full93-row judge or Oracle score. Native-frame inspection was exercised; virtual-realm tooling and proactive dirty-action prevention remain unexercised alternatives. Automation timing does not measure fullLLM judge overhead. All4owned disposable containers exited; preview3420 remains running.\n`);
console.log(JSON.stringify({summary:summaryRef,map:mapRef,binding:bindingRef,focused_outcomes:9,expected_cases:4},null,2));
