const assert=require('node:assert/strict');
const fs=require('node:fs');
const {spawn,execFileSync}=require('node:child_process');
const {randomUUID}=require('node:crypto');
const {chromium}=require('/usr/local/lib/node_modules/@playwright/mcp/node_modules/playwright');
const results=[];let base='http://127.0.0.1:3000',browser,child,ada,nora;
async function check(name,fn){await fn();results.push({name,passed:true});console.log('PASS '+name);}
async function api(path,token,body,method){const r=await fetch(base+path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',Connection:'close',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};}
async function login(name){const r=await api('/api/auth/login',null,{email:name+'@coursemark.example',password:'Coursemark!2026'});assert.equal(r.status,200);return r.data.token;}
async function get(path,t=ada){const r=await api(path,t);assert.equal(r.status,200);return r.data;}
async function snapshot(){return Promise.all(['/api/me','/api/assessments','/api/attempts','/api/audit','/api/outcomes'].map(path=>get(path)));}
async function write(path,body={},token=ada){const r=await api(path,token,{...body,expected_revision:(await get('/api/me',token)).revision,operation_id:randomUUID()});assert(r.status===200||r.status===201,JSON.stringify(r));return r;}
const draft=title=>({course_id:'BIO-214',title,opens_at:'2026-09-03T09:00:00Z',due_at:'2026-09-03T11:00:00Z',duration_minutes:25,max_attempts:1});
async function uiLogin(p,name){await p.goto(base);await p.locator('#login-email').fill(name+'@coursemark.example');await p.locator('#login-password').fill('Coursemark!2026');await p.locator('#login-form button[type=submit]').click();await p.locator('#app-view').waitFor({state:'visible'});}
async function uiDraft(p,title){await p.locator('.tab[data-view=assessments]').click();await p.locator('#new-assessment').click();const f=p.locator('#assessment-form');await f.locator('[name=title]').fill(title);await f.locator('[name=opens_at]').fill('2026-09-03T09:00');await f.locator('[name=due_at]').fill('2026-09-03T11:00');}
async function action(p,selector,path){const waiting=p.waitForResponse(r=>r.url().endsWith(path)&&r.request().method()!=='GET');await p.locator(selector).click();const r=await waiting;await r.finished();return r;}
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});ada=await login('ada.mensah');nora=await login('nora.kim');
 await check('fresh seed imports both explicit zero grades and renders released 5/10 feedback',async()=>{
  const at=(await get('/api/attempts',nora)).attempts.find(a=>a.id==='AT-102');assert.equal(at.status,'graded');assert.equal(at.feedback_status,'released');assert.equal(at.total_score,5);assert.deepEqual(at.grades.map(g=>[g.criterion_id,g.score,g.graded_by]),[['RC-3',0,'user_1'],['RC-4',0,'user_1']]);assert.equal(at.grades.reduce((n,g)=>n+g.score,0),at.rubric_score);
  const p=await browser.newPage({viewport:{width:375,height:812}});await uiLogin(p,'nora.kim');await p.locator('.tab[data-view=gradebook]').click();const row=p.locator('#gradebook-list .panel').filter({hasText:'AT-102'});assert.match(await row.innerText(),/5\/10/);assert.equal(await row.locator('.released-feedback p').count(),2);assert.match(await row.innerText(),/0\/2/);assert.match(await row.innerText(),/0\/3/);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'/evidence/seeded-released-feedback-mobile.png',fullPage:true,animations:'disabled'});await p.close();
 });
 await check('seed grades and their release state survive restart without duplicate grades or audit events',async()=>{const before=await snapshot();execFileSync('bash',['/tests/app-lifecycle.sh','restart']);assert.deepEqual(await snapshot(),before);assert.equal((await get('/api/attempts',nora)).attempts.find(a=>a.id==='AT-102').grades.length,2);});
 const dir=fs.mkdtempSync('/tmp/coursemark-seed-variant-');fs.cpSync('/app',dir,{recursive:true,filter:p=>!p.includes('coursemark.db')});
 const variant=JSON.parse(fs.readFileSync('/assets/artifacts/coursemark_seed.json','utf8'));variant.rubric_grades[0].score=1;variant.rubric_grades[1].score=2;variant.attempts.find(a=>a.id==='AT-102').rubric_score=3;fs.writeFileSync(dir+'/variant-seed.json',JSON.stringify(variant));
 let code=fs.readFileSync(dir+'/server.js','utf8');assert(code.includes('throw httpError(409, "Course updated in another tab.");'));code=code.replace('throw httpError(409, "Course updated in another tab.");','throw httpError(412, "Course updated in another tab.");');fs.writeFileSync(dir+'/server.js',code);
 code=fs.readFileSync(dir+'/outcomes.js','utf8');assert(code.includes('throw httpError(409,"Release preview is stale.'));code=code.replace('throw httpError(409,"Release preview is stale.','throw httpError(412,"Release preview is stale.');fs.writeFileSync(dir+'/outcomes.js',code);
 code=fs.readFileSync(dir+'/public/app.js','utf8').replaceAll('error.status === 409','[409, 412].includes(error.status)');fs.writeFileSync(dir+'/public/app.js',code);
 let childError='';child=spawn(process.execPath,[dir+'/server.js'],{cwd:dir,env:{...process.env,PORT:'3001',DB_PATH:dir+'/variant.db',SEED_PATH:dir+'/variant-seed.json'},stdio:['ignore','ignore','pipe']});child.stderr.on('data',b=>childError+=b.toString());base='http://127.0.0.1:3001';
 let ready=false;for(let i=0;i<100;i++){try{ready=(await api('/api/health')).status===200;if(ready)break;}catch{}await new Promise(r=>setTimeout(r,50));}assert(ready,childError);ada=await login('ada.mensah');nora=await login('nora.kim');
 await check('fresh-database variant imports changed seed grades rather than hardcoding zero totals',async()=>{const at=(await get('/api/attempts',nora)).attempts.find(a=>a.id==='AT-102');assert.deepEqual(at.grades.map(g=>g.score),[1,2]);assert.equal(at.rubric_score,3);assert.equal(at.total_score,8);assert.equal((await get('/api/outcomes',nora)).rows[0].cells.find(c=>c.assessment_id==='A-03').awarded,8);});
 await check('contract-valid HTTP 412 stale write preserves state, receipt and visible fresh retry',async()=>{
  const p=await browser.newPage(),q=await browser.newPage();await uiLogin(p,'ada.mensah');await uiLogin(q,'ada.mensah');await uiDraft(p,'412 draft A');await uiDraft(q,'412 draft B');assert.equal((await action(p,'#assessment-form button[type=submit]','/api/assessments')).status(),201);const before=await snapshot();
  const r=await action(q,'#assessment-form button[type=submit]','/api/assessments');assert.equal(r.status(),412);await q.locator('#assessment-error').filter({hasText:'another tab'}).waitFor();assert.equal(await q.locator('#assessment-form [name=title]').inputValue(),'412 draft B');assert.deepEqual(await snapshot(),before);const request=r.request(),body=request.postDataJSON(),token=request.headers().authorization.slice(7),data=await r.json();assert.equal((await action(q,'#assessment-form button[type=submit]','/api/assessments')).status(),201);const stable=await snapshot();assert.deepEqual(await api('/api/assessments',token,body),{status:412,data});assert.deepEqual(await snapshot(),stable);await p.close();await q.close();
 });
 await check('contract-valid HTTP 412 stale release binding refuses fresh-revision bypass and supports UI recovery',async()=>{
  const p=await browser.newPage();await uiLogin(p,'ada.mensah');await p.locator('.tab[data-view=gradebook]').click();await p.locator('#open-release-batch').click();await p.locator('[data-release-choice="AT-103"]').check();const preview=await action(p,'#preview-release','/api/release-plans');assert.equal(preview.status(),200);await p.locator('#release-preview').filter({hasText:'Ben Okafor'}).waitFor();const plan=await preview.json();await write('/api/assessments',draft('Intervening 412 plan change'));const before=await snapshot();
  const rejected=await api('/api/release-plans/commit',ada,{plan_id:plan.plan_id,expected_revision:(await get('/api/me')).revision,operation_id:randomUUID()});assert.equal(rejected.status,412);assert.deepEqual(await snapshot(),before);assert.equal((await action(p,'#commit-release','/api/release-plans/commit')).status(),412);await p.locator('#release-batch-error').filter({hasText:/another tab|stale/}).waitFor();assert(await p.locator('#commit-release').isDisabled());assert.equal((await action(p,'#preview-release','/api/release-plans')).status(),200);await p.locator('#release-preview').filter({hasText:'Ben Okafor'}).waitFor();assert.equal((await action(p,'#commit-release','/api/release-plans/commit')).status(),200);assert.equal((await get('/api/attempts')).attempts.find(a=>a.id==='AT-103').feedback_status,'released');await p.close();
 });
 child.kill();await browser.close();fs.writeFileSync('/evidence/seed-runtime.json',JSON.stringify({kind:'Local seed and compatible-status implementation checks, not model grades',results},null,2));
})().catch(async error=>{console.error(error);results.push({passed:false,error:String(error),stack:error.stack});fs.writeFileSync('/evidence/seed-runtime.json',JSON.stringify({results},null,2));if(child)child.kill();if(browser)await browser.close();process.exitCode=1;});
