const express=require('express');
const crypto=require('crypto');
const { DatabaseSync }=require('node:sqlite');
const path=require('path');
const app=express();
const db=new DatabaseSync('/app/brickfall.db');
const pub=path.join('/app','public');
app.use(express.json({limit:'2mb'})); app.use(express.static(pub));
const all=(s,p=[])=>db.prepare(s).all(...p), get=(s,p=[])=>db.prepare(s).get(...p), run=(s,p=[])=>db.prepare(s).run(...p), exec=s=>db.exec(s);
const now=()=>new Date().toISOString(), tok=()=>crypto.randomBytes(32).toString('hex'), uid=()=>crypto.randomUUID(), sha=s=>crypto.createHash('sha256').update(s).digest('hex');
exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,email TEXT UNIQUE,name TEXT,initials TEXT,password_salt TEXT,password_hash TEXT,highest_level INTEGER,best_score INTEGER);CREATE TABLE IF NOT EXISTS levels(level INTEGER PRIMARY KEY,name TEXT,base_speed REAL,speed_cap REAL,accent TEXT);CREATE TABLE IF NOT EXISTS bricks(level INTEGER,row INTEGER,column INTEGER,type TEXT,drop_type TEXT,PRIMARY KEY(level,row,column));CREATE TABLE IF NOT EXISTS leaderboard(id INTEGER PRIMARY KEY AUTOINCREMENT,initials TEXT,score INTEGER,level INTEGER,achieved_at TEXT,email TEXT);CREATE TABLE IF NOT EXISTS constants(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE IF NOT EXISTS tokens(token TEXT PRIMARY KEY,user_id INTEGER,created_at TEXT,revoked_at TEXT);CREATE TABLE IF NOT EXISTS runs(run_id TEXT PRIMARY KEY,user_id INTEGER,status TEXT,revision INTEGER,snapshot_json TEXT,updated_at TEXT,finished_at TEXT,operation_id TEXT UNIQUE);CREATE TABLE IF NOT EXISTS run_receipts(operation_id TEXT PRIMARY KEY,user_id INTEGER,status_code INTEGER,response_json TEXT,payload_hash TEXT,created_at TEXT);CREATE TABLE IF NOT EXISTS terminal_runs(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,run_id TEXT,outcome TEXT,level INTEGER,score INTEGER,finished_at TEXT,snapshot_json TEXT);`);
const auth=req=>{const m=(req.headers.authorization||'').match(/^Bearer\s+([a-f0-9]{64})$/); if(!m) return null; return get('SELECT t.token,t.user_id,u.email,u.name,u.initials,u.highest_level,u.best_score FROM tokens t JOIN users u ON u.id=t.user_id WHERE t.token=? AND t.revoked_at IS NULL',[m[1]])||null;};
const need=fn=>async(req,res)=>{try{const u=auth(req); if(!u) return res.status(401).json({error:'sign-in required'}); req.user=u; await fn(req,res);}catch(e){console.error(e);res.status(500).json({error:'server error'});} };
const c=()=>Object.fromEntries(all('SELECT key,value FROM constants').map(r=>[r.key,r.value]));
const runRow=uid=>get('SELECT * FROM runs WHERE user_id=? ORDER BY updated_at DESC LIMIT 1',[uid]);
const snap=r=>r?JSON.parse(r.snapshot_json):null;
function receipt(op,user,body){const e=get('SELECT * FROM run_receipts WHERE operation_id=?',[op]); if(e){const h=sha(JSON.stringify(body||{})); if(e.payload_hash!==h) return {conflict:true}; return {existing:e};} return null;}
function saveReceipt(op,user,status,response,body){run('INSERT INTO run_receipts VALUES (?,?,?,?,?,?)',[op,user,status,JSON.stringify(response),sha(JSON.stringify(body||{})),now()]);}
app.get('/api/bootstrap',need(async(req,res)=>res.json({user:req.user,levels:all('SELECT * FROM levels ORDER BY level'),bricks:all('SELECT * FROM bricks'),leaderboard:all('SELECT initials,score,level,achieved_at FROM leaderboard ORDER BY score DESC, achieved_at ASC LIMIT 10'),constants:c(),run:snap(runRow(req.user.user_id))})))
app.post('/api/sign-in',async(req,res)=>{const {email,password}=req.body||{}; const u=get('SELECT * FROM users WHERE email=?',[email]); if(!u||sha(u.password_salt+password)!==u.password_hash) return res.status(401).json({error:'invalid credentials'}); const t=tok(); run('INSERT INTO tokens(token,user_id,created_at,revoked_at) VALUES (?,?,?,NULL)',[t,u.id,now()]); res.json({token:t,user:{id:u.id,email:u.email,name:u.name,initials:u.initials,highest_level:u.highest_level,best_score:u.best_score}});});
app.post('/api/sign-out',need(async(req,res)=>{run('UPDATE tokens SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL',[now(),req.user.user_id]); res.json({ok:true});}));
app.get('/api/me',need(async(req,res)=>res.json({user:req.user,run:snap(runRow(req.user.user_id))})))
app.post('/api/run/start',need(async(req,res)=>{const b=req.body||{}; const rr=receipt(b.operationId,req.user.user_id,b); if(rr?.conflict) return res.status(409).json({error:'operation id reuse with different payload'}); if(rr?.existing) return res.status(rr.existing.status_code).json(JSON.parse(rr.existing.response_json)); const lvl=get('SELECT * FROM levels WHERE level=?',[b.level]); if(!lvl) return res.status(400).json({error:'invalid level'}); const prev=runRow(req.user.user_id); if(prev && (b.expectedRevision||1)!==prev.revision) return res.status(409).json({error:'stale revision',revision:prev.revision,run:snap(prev)}); const runId=uid(); const sn={runId,level:b.level,score:0,lives:3,combo:1,nextExtraLife:20000,revision:(b.expectedRevision||1)+1,status:'playing',balls:[{id:'b1',x:400,y:520,vx:220,vy:-360,waiting:false}],drops:[],paddle:{x:340,width:120,sticky:false},power:null,message:'Run started',unlockedLevel:Math.min(req.user.highest_level,b.level),activeRun:true}; run('INSERT OR REPLACE INTO runs VALUES (?,?,?,?,?,?,?,?)',[runId,req.user.user_id,'active',sn.revision,JSON.stringify(sn),now(),null,b.operationId]); const resp={run:sn}; saveReceipt(b.operationId,req.user.user_id,200,resp,b); res.json(resp);}));
app.post('/api/run/save',need(async(req,res)=>{const b=req.body||{}; const rr=receipt(b.operationId,req.user.user_id,b); if(rr?.conflict) return res.status(409).json({error:'operation id reuse with different payload'}); if(rr?.existing) return res.status(rr.existing.status_code).json(JSON.parse(rr.existing.response_json)); const cur=runRow(req.user.user_id); if(!cur) return res.status(400).json({error:'no active run'}); if(b.expectedRevision!==cur.revision) return res.status(409).json({error:'stale revision',revision:cur.revision,run:snap(cur)}); const sn=b.run||snap(cur); sn.revision=cur.revision+1; run('UPDATE runs SET status=?,revision=?,snapshot_json=?,updated_at=?,operation_id=? WHERE run_id=?',['active',sn.revision,JSON.stringify(sn),now(),b.operationId,cur.run_id]); const resp={run:sn}; saveReceipt(b.operationId,req.user.user_id,200,resp,b); res.json(resp);}));
app.post('/api/run/finish',need(async(req,res)=>{const b=req.body||{}; const rr=receipt(b.operationId,req.user.user_id,b); if(rr?.conflict) return res.status(409).json({error:'operation id reuse with different payload'}); if(rr?.existing) return res.status(rr.existing.status_code).json(JSON.parse(rr.existing.response_json)); const cur=runRow(req.user.user_id); if(!cur) return res.status(400).json({error:'no active run'}); if(b.expectedRevision!==cur.revision) return res.status(409).json({error:'stale revision',revision:cur.revision,run:snap(cur)}); const sn=b.run||snap(cur); sn.revision=cur.revision+1; const outcome=b.outcome||sn.status||'completed'; run('UPDATE runs SET status=?,revision=?,snapshot_json=?,updated_at=?,finished_at=?,operation_id=? WHERE run_id=?',[outcome,sn.revision,JSON.stringify(sn),now(),now(),b.operationId,cur.run_id]); run('INSERT INTO terminal_runs(user_id,run_id,outcome,level,score,finished_at,snapshot_json) VALUES (?,?,?,?,?,?,?)',[req.user.user_id,cur.run_id,outcome,sn.level,sn.score,now(),JSON.stringify(sn)]); const u=get('SELECT * FROM users WHERE id=?',[req.user.user_id]); if(sn.score>u.best_score) run('UPDATE users SET best_score=? WHERE id=?',[sn.score,req.user.user_id]); if(sn.level>u.highest_level) run('UPDATE users SET highest_level=? WHERE id=?',[sn.level,req.user.user_id]); run('DELETE FROM runs WHERE run_id=?',[cur.run_id]); const lb=all('SELECT initials,score,level,achieved_at FROM leaderboard ORDER BY score DESC, achieved_at ASC'); const resp={terminal:{outcome,runId:cur.run_id,level:sn.level,score:sn.score,finishedAt:now()}, leaderboard:lb.slice(0,10)}; saveReceipt(b.operationId,req.user.user_id,200,resp,b); res.json(resp);}));
app.get('/api/lab',need(async(req,res)=>res.json({drills:all('SELECT key,value FROM constants')})))
app.listen(3000,()=>console.log('Brickfall listening on 3000'));
