const fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium}=require('/usr/local/lib/node_modules/@playwright/mcp/node_modules/playwright');
const out='/work/commerce',report={checks:[],pageErrors:[]};let browser,page;
const complete=async values=>page.waitForFunction(values=>JSON.stringify([...document.querySelectorAll('.summary dd')].map(e=>Number(e.textContent.replace(/[^0-9.]/g,''))))===JSON.stringify(values),values);
async function add(size,qty){await page.getByRole('button',{name:'The prints',exact:true}).click();await page.getByRole('button',{name:'View Night Ferry',exact:true}).click();await page.getByRole('button',{name:new RegExp('^'+size)}).click();const input=page.getByRole('spinbutton',{name:'Quantity for Night Ferry '+size+' to add',exact:true});await input.fill(String(qty));await input.blur();assert.match(await page.locator('.trade-note').innerText(),/5\+.*36\.25|5\+.*55\.95/);await page.getByRole('button',{name:'Add to basket',exact:true}).click();await page.getByRole('status').filter({hasText:'added to your basket'}).waitFor();}
async function lookup(ref){await page.getByRole('button',{name:'Track an order',exact:true}).click();await page.getByLabel('Order reference',{exact:true}).fill(ref);await page.getByRole('button',{name:'Find order',exact:true}).click();await page.getByText(ref,{exact:true}).waitFor();}
async function main(){browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium'});page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.pageErrors.push(e.message));await page.goto('http://localhost:3000');await page.locator('.print-card').first().waitFor();await page.getByRole('button',{name:'View Allotment',exact:true}).click();assert.match(await page.getByRole('button',{name:/^A3/}).innerText(),/37\.95/);assert(await page.getByRole('button',{name:'Sold out',exact:true}).isDisabled());report.checks.push({id:'Allotment sold-out button',passed:true});
 await add('A3',4);await add('A2',1);await page.getByRole('button',{name:/Open basket,/}).click();await complete([234.5,0,4.95,239.45]);const a3=page.locator('.basket-line').filter({has:page.getByRole('spinbutton',{name:'Quantity for Night Ferry A3',exact:true})});const a2=page.locator('.basket-line').filter({has:page.getByRole('spinbutton',{name:'Quantity for Night Ferry A2',exact:true})});assert.match(await a3.innerText(),/42\.50 each/);assert.match(await a2.innerText(),/64\.50 each/);await page.getByRole('button',{name:'Increase Night Ferry A3',exact:true}).click();await complete([277,31.25,4.95,250.70]);assert.match(await a3.innerText(),/36\.25 each/);assert.match(await a3.innerText(),/181\.25/);assert.match(await a3.innerText(),/Trade price applied/);assert.match(await a2.innerText(),/64\.50 each/);await page.getByRole('button',{name:'Decrease Night Ferry A3',exact:true}).click();await complete([234.5,0,4.95,239.45]);assert.match(await a3.innerText(),/42\.50 each/);assert.match(await a2.innerText(),/64\.50 each/);while(await page.getByRole('button',{name:/^Remove /}).count())await page.getByRole('button',{name:/^Remove /}).first().click();report.checks.push({id:'Exact Night Ferry threshold changes same basket line 4 to 5 to 4',passed:true});
 const evidence=JSON.parse(fs.readFileSync(out+'/results.json','utf8'));const mixed=evidence.requests.find(r=>r.purpose==='ordinary UI positive purchase'&&r.request.address.name.includes('Mixed trade')).body;await lookup(mixed.reference);await complete([326.35,31.25,4.95,300.05]);const receipt=await page.locator('.receipt-lines').innerText();for(const text of['Long Field','Kiln','Two Weathers','37.95','36.25','181.25'])assert(receipt.includes(text));for(const key of['address_name','address_line1','address_city','address_postcode'])assert((await page.locator('.receipt-address').innerText()).includes(mixed[key]));await page.screenshot({path:out+'/mixed-receipt-exact-lines.png',fullPage:true});report.checks.push({id:'Mixed receipt visible per-line prices and saved address',passed:true,reference:mixed.reference});
 await lookup('RP-100001');await page.getByRole('button',{name:'Track an order',exact:true}).click();await page.getByLabel('Order reference',{exact:true}).fill('RP-999999');await page.getByRole('button',{name:'Find order',exact:true}).click();await page.getByRole('heading',{name:'Order not found',exact:true}).waitFor();assert.equal(await page.locator('.receipt-lines').count(),0);await lookup('RP-100001');await complete([70,0,3.2,73.2]);report.checks.push({id:'Known unknown known lookup UI recovery',passed:true});assert.deepEqual(report.pageErrors,[]);report.passed=true;
}
main().catch(e=>{report.passed=false;report.error=e.stack;console.error(e);process.exitCode=1}).finally(async()=>{fs.writeFileSync(out+'/remaining-ui-legs-results.json',JSON.stringify(report,null,2));if(browser)await browser.close();console.log(JSON.stringify({passed:report.passed,checks:report.checks.length}));});
