'use strict';
// Read-only reconstruction; only this review directory receives output.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=process.cwd(),base='deliverables/colderwater-playground-devtools';
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p))),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const ref=(p,lines)=>({path:p,sha256:sha(p),lines});
const order=['hardening-2026-09-26','instruction-hygiene-fix-2026-09-26','rubric-fix-2026-09-26','network-policy-fix-2026-09-26','full-qc-2026-09-27','cross-check-2026-09-27','interaction-keyboard-fix-2026-09-27','metadata-cleanup-2026-09-27','eight-issue-fix-2026-09-27','final-cross-check-2026-09-27','two-findings-fix-2026-09-27','structural-review-2026-09-27','positive-controls-fix-2026-09-27'];
const changes=[
  'First preserved hardened candidate; 24 Functional criteria. Local QC is not a platform result.',
  'Only six criterion IDs and matching names changed, removing nine public-text whole-token collisions; 49 other task files unchanged.',
  'Ten reported findings: owner voice, actual grader-language leak, missing coverage, bundled outcomes and weak gates; Functional 24 to 32. Golden installer lifecycle repaired.',
  'Allowed app/CDN assets while retaining authored-snippet network prohibition; seven files changed. Trigger was a Ridgeline finding also applicable here, not an independently documented Colderwater QC round.',
  'Three reported screenshot flags/two causes: unasked supersession notice and missing HTTP privacy; additional local CSS-handler/debounce/presentation issues. Functional 32 to 33.',
  'Local cross-check only: false-success restart helper and harmless privacy-redirect false failure repaired. No new platform attempt asserted.',
  'Two reported gaps: completed-preview later interaction contract and pointer-free example/library route. Golden keyboard help added; runtime unchanged.',
  'Only four descriptive task.toml fields changed; 49 other files unchanged. Known final cleanup issue explicitly still pending.',
  'Eight reported categories: unasked loop responsiveness/escape documentation, coupled outcomes, browser privacy decision feasibility, negative windows/real stale editor, workload and metadata; Functional 33 to 35. Bounded cleanup/report handling also repaired.',
  'Local cross-check only: omitted-empty-reasoning compatibility, optional pending DOM/input, positive padded title controls, latest-interaction rollback, completed Stop and saved-example copy. No platform attempt asserted.',
  'Two reported findings: public exact privacy probe leak/undercoverage and restart/deletion independence. Nine private candidates, independent restart New/Save flow, three deletion rows; Functional 35 to 37.',
  'Reported timeout-fit and independence failures: shared 37 protocols/seven phases, 88 scored outcomes, fewer nominal Runs; all 23 golden files unchanged.',
  'Reported positive-control omissions and privacy classification overlap: sixteen descriptors retain controls, ordered terminal privacy decisions and conditional fallback setup; counts/weights unchanged.'
];
const archives=[];let previous=null;
for(let i=0;i<order.length;i++){
  const dir=base+'/'+order[i],manifestPath=fs.existsSync(dir+'/candidate_manifest.json')?dir+'/candidate_manifest.json':dir+'/review-candidate/candidate_manifest.json';
  const m=read(manifestPath),zip=path.posix.dirname(manifestPath)+'/'+m.archive;assert.equal(sha(zip),m.sha256,'Archive changed: '+zip);
  const current=m.source_sha256,delta=previous?{changed:Object.keys(current).filter(p=>p in previous&&current[p]!==previous[p]),added:Object.keys(current).filter(p=>!(p in previous)),removed:Object.keys(previous).filter(p=>!(p in current))}:null;
  archives.push({sequence:i+1,directory:order[i],sha256:m.sha256,archive:ref(zip),manifest:ref(manifestPath),files:m.files,bytes:m.bytes,functional_criteria:m.dimensions.functional.criteria,functional_weight:m.dimensions.functional.weight,change_summary:changes[i],exact_file_delta_from_prior_retained_archive:delta,platform_submission_proven:false});previous=current;
}
const byDir=Object.fromEntries(archives.map(a=>[a.directory,a]));
const source=(dir,file,lines)=>ref(base+'/'+dir+'/'+file,lines);
const episode=(id,prior,repair,linkage,reported,fix,sources)=>({id,kind:'Documented feedback episode, not an authenticated platform run record',reported_against_archive_sha256:prior?byDir[prior].sha256:null,archive_linkage:linkage,repair_archive_sha256:byDir[repair].sha256,reported_findings:reported,repair_summary:fix,evidence:sources,platform_run_id:null,platform_qc_version:null,platform_settings:null,raw_screenshot_or_platform_export_available_in_this_review:false});
const episodes=[
  episode('E1','hardening-2026-09-26','instruction-hygiene-fix-2026-09-26','Explicit old/new hashes in local crosswalk and explicit platform-static-failure attribution; no raw platform submission record.',['Literal instruction/criterion-ID collision: six ordinary public words were IDs, matching nine public lines.'],'Rename only private IDs/names; add actual whole-token scan. This does not repair separate semantic grader-language leaks.',[source('instruction-hygiene-fix-2026-09-26','CRITERION_ID_CROSSWALK.md','3-20'),source('instruction-hygiene-fix-2026-09-26','QC_FINAL.md','5-20')]),
  episode('E2',null,'rubric-fix-2026-09-26','The transcript says previously uploaded task after the ID-only repair, but does not itself give that uploaded ZIP hash. d250 is the chronological local predecessor, not independently authenticated submission identity.',['instruction_is_a_natural_product_request','instruction_preserves_natural_human_voice','instruction_leaks_no_grader_machinery','dimensions_cover_every_graded_requirement','criteria_are_independent_and_noncontradictory','global_browser_gate_is_present_and_correct_in_every_dimension','floor_is_low_for_shells_mocks_and_stuffing','gates_apply_before_shaping_and_carry_no_reward_mass','dimension_and_criterion_weights_are_honest','dimension_prompts_are_accurate_and_consistent'],'Ten failures/43 passes transcribed; owner voice, verifier-files leak, missing families/dirty cases, independent credit and authored-Run/server-library gates repaired.',[source('rubric-fix-2026-09-26','PLATFORM_FAILURES.md','3-18'),source('rubric-fix-2026-09-26','FIX_SUMMARY.md','3-25')]),
  episode('E3',null,'full-qc-2026-09-27','QC report states latest three screenshot flags; Functional delta identifies the local baseline as 998f. The raw screenshot-to-ZIP association is not preserved.',['Three flags, two documented causes: unrequested supersession notification; missing HTTP confidentiality coverage. Exact three check IDs are not transcribed in the inspected report.'],'Make supersession notice optional; add bounded HTTP privacy observation. Also locally discover CSS/debounce/presentation issues.',[source('full-qc-2026-09-27','QC_FINAL.md','11-25'),source('full-qc-2026-09-27','FUNCTIONAL_DELTA.md','3-17')]),
  episode('E4','cross-check-2026-09-27','interaction-keyboard-fix-2026-09-27','Local semantic report explicitly associates the two latest screenshot findings with d254. No raw platform result metadata.',['Ambiguous completed-preview interaction after the original five-second budget.','Keyboard coverage did not prove pointer-free access to examples and saved library.'],'Clarify public later-interaction lifecycle and exercise delayed click/key/input; perform actual keyboard route; add golden escape help.',[source('interaction-keyboard-fix-2026-09-27','SEMANTIC_FIX_REVIEW.md','3-15'),source('interaction-keyboard-fix-2026-09-27','KEYBOARD_RECHECK.md','3-15')]),
  episode('E5',null,'eight-issue-fix-2026-09-27','Repair report calls these reported failures and supersedes metadata-only09f; historical handoff identifies09f as current. Direct submitted-ZIP identity is not independently present.',['Deliverables/runtime contract','Achievability/ambiguity','Timeouts fit the work','Unrequired grading','Independent criteria','Browser-decidable outcomes','Self-consistent descriptions','Distinct/authored task'],'Remove loop-host responsiveness and mandatory escape documentation; split dispatch/late interaction and clock budgets; replace byte-classifier privacy with reserved paths; correct negative windows and real dirty-editor proof; simplify work and repair cleanup/report handling.',[source('eight-issue-fix-2026-09-27','QC_FINAL.md','3-27'),source('eight-issue-fix-2026-09-27','functional/FUNCTIONAL_REPAIRS.md','5-22'),source('eight-issue-fix-2026-09-27','previous_handoff.md','3-20')]),
  episode('E6','final-cross-check-2026-09-27','two-findings-fix-2026-09-27','Privacy design review explicitly names rejected63a05; final QC says two platform findings repaired and supersedes63a05.',['instruction_leaks_no_grader_machinery: exact public three-path allow/deny boundary could be gamed while exposing other working files.','criteria_are_independent_and_noncontradictory: Duplicate/Delete prerequisites poisoned restart credit; normal/stale/deleted-identity deletion protections bundled.'],'Return public privacy text to categories and privately sample nine paths with public-role alternatives; independent New/Save restart; split deletion1+1+1.',[source('two-findings-fix-2026-09-27','QC_FINAL.md','1-15'),source('two-findings-fix-2026-09-27','semantics/privacy-design-review.md','1-15'),source('two-findings-fix-2026-09-27','qc_final_findings.json')]),
  episode('E7','two-findings-fix-2026-09-27','structural-review-2026-09-27','README explicitly says platform rejected5d0 for the two named checks. No run ID/QC version/settings.',['timeouts_fit_the_work','criteria_are_independent_and_noncontradictory'],'Separate37 bundles into88 outcomes with shared protocols; split import/server validation, trim/collision/case, startup/example separation and dispatch/CSS handlers. Reduce repeated setup; full LLM timing remains unmeasured.',[source('structural-review-2026-09-27','README.md','3-25'),source('structural-review-2026-09-27','QC_FINAL.md')]),
  episode('E8','structural-review-2026-09-27','positive-controls-fix-2026-09-27','README explicitly says two platform findings against7d693e9. Raw platform execution metadata absent.',['Negative-control sufficiency: dead Auto-run could earn OFF silence; wiped CSS preview could earn no-handler-output credit.','Ambiguous privacy classification: successful unknown delivery could be both exposure and incomplete.'],'Require actual positive control facts without sibling verdict inheritance; sixteen descriptors audited; ordered terminal S06 classification and independent fallback controls.',[source('positive-controls-fix-2026-09-27','README.md','3-17'),source('positive-controls-fix-2026-09-27','QC_FINAL.md','3-13'),source('positive-controls-fix-2026-09-27','change_summary.json')]),
];
const repeatAnalysis=[
  {topic:'Instruction hygiene/leakage',classification:'Same broad family, different concrete witnesses',detail:'E1 literal ID collisions were removed. E2 actual text verifier files remained because an ID-only change never addressed it. E6 newly public exact privacy probes exposed the evaluation boundary. Later leakage does not show the renamed IDs regressed.',evidence:[source('instruction-hygiene-fix-2026-09-26','CRITERION_ID_CROSSWALK.md'),source('rubric-fix-2026-09-26','PLATFORM_FAILURES.md'),source('two-findings-fix-2026-09-27','semantics/privacy-design-review.md')]},
  {topic:'Independence',classification:'Repeated check ID with different witnesses, plus incomplete breadth of earlier repairs',detail:'E2 split export/import, isolation/unsupported, native/in-app warnings and four error paths. E5 split newly combined dispatch/late interaction and run/interaction clocks. E6 found restart prerequisites and deletion bundling. E7 found import/filename validation, trim/case/collision, startup/example and dispatch/inert copying. Earlier narrow splits did not prove all remaining bundles independent; the reports do not establish the exact repaired export/import conjunction returned.',evidence:[source('rubric-fix-2026-09-26','PLATFORM_FAILURES.md'),source('eight-issue-fix-2026-09-27','functional/FUNCTIONAL_REPAIRS.md'),source('two-findings-fix-2026-09-27','QC_FINAL.md'),source('structural-review-2026-09-27','README.md')]},
  {topic:'Coverage',classification:'Same broad check, different missing observations',detail:'Unsupported families/stale rename/dirty transitions were early omissions; HTTP exposure was another; keyboard route was another. A coverage map confirming existing checks were justified did not establish all promises had observations.',evidence:[source('rubric-fix-2026-09-26','REQUIREMENT_COVERAGE.md','9'),source('full-qc-2026-09-27','QC_FINAL.md'),source('interaction-keyboard-fix-2026-09-27','SEMANTIC_FIX_REVIEW.md')]},
  {topic:'Timeout fit',classification:'Repeated unresolved measurement risk',detail:'E5 reduced work but explicitly left hosted completion unmeasured. E7 again reported timeout fit; the later README says this was a source-review risk, not an observed timed-out Oracle. Current663e QC still marks timeout fit Not exercised/P1. The90.16s local automation run excludes LLM orchestration and cannot close it.',evidence:[source('eight-issue-fix-2026-09-27','QC_FINAL.md'),source('structural-review-2026-09-27','README.md'),source('positive-controls-fix-2026-09-27','QC_FINAL.md')]},
  {topic:'Positive controls detached by88-outcome split',classification:'Documented regression introduced by a repair',detail:'Before the split, broader Auto-run and language criteria included the working positive path. The7d short OFF-silence and CSS-inert descriptions could award credit to dead Auto-run or erased content. The positive-controls README explicitly identifies separating credit as the cause; current controls and actual mutants repair it.',evidence:[source('positive-controls-fix-2026-09-27','README.md'),source('positive-controls-fix-2026-09-27','change_summary.json'),source('positive-controls-fix-2026-09-27','golden/FOCUSED_PROOF_SUMMARY.json')]},
  {topic:'Exact reserved privacy path contract',classification:'Documented regression/undercoverage introduced by a prior fix',detail:'09f public text described private categories and allowed similarly named public scripts. The eight-issue repair replaced that with exact reserved /app.db,/server.js,/package.json and excluded other filenames. The63a rejection then showed deny-only-three could pass while leaking companion/project/repository files;5d restored category-level public requirements.',evidence:[source('metadata-cleanup-2026-09-27','archive-check-09f4f6cb3647/colderwater-playground-devtools/environment/instructions/security.md'),source('final-cross-check-2026-09-27','archive-check-63a05a5e4ebf/colderwater-playground-devtools/environment/instructions/security.md'),source('two-findings-fix-2026-09-27','semantics/privacy-design-review.md')]},
  {topic:'Privacy ambiguity versus exposure',classification:'Contradiction in the public-role repair persisted into the shared protocol rewrite',detail:'The5d privacy design accepted unresolved credible public-role ambiguity but separately called any successful standalone delivery without established role/fallback an exposure.7d carried this competing classification forward.663e makes accepted outcomes, narrow terminal incomplete, and observed exposure mutually exclusive. This is distinct from the earlier missing-path coverage defect.',evidence:[source('two-findings-fix-2026-09-27','semantics/privacy-design-review.md'),source('structural-review-2026-09-27','golden/frozen_final_inputs.json'),source('positive-controls-fix-2026-09-27','README.md')]},
];
const excludedEvents=[
  {event:'App CDN/network policy correction',reason:'Explicitly triggered by feedback on the other task, then applied here; not counted as an independent Colderwater platform QC episode.',evidence:source('network-policy-fix-2026-09-26','FIX_SUMMARY.md','7')},
  {event:'b34 to d254 cross-check',reason:'Local restart/redirect findings, expressly no platform attempt.',evidence:source('cross-check-2026-09-27','QC_FINAL.md')},
  {event:'a017 to63a cross-check',reason:'Local compatibility and fairness findings, expressly no platform attempt.',evidence:source('final-cross-check-2026-09-27','QC_FINAL.md')},
  {event:'0035,9160,9b8567 to663e intermediate positive-control candidates',reason:'Local frozen-source edits during one repair, not repeated platform runs. Preserved manifests prove differing prompt/descriptor inputs.',evidence:source('positive-controls-fix-2026-09-27','golden/FOCUSED_PROOF_SUMMARY.json')},
  {event:'Local browser false/incomplete then corrected/composite results',reason:'Known external driver issues (CRLF/selector/feedback/status collision) with preserved diagnostics. They do not compare platform QC under identical settings.',evidence:[source('structural-review-2026-09-27','golden/RUNTIME_PROOF_SUMMARY.json'),source('positive-controls-fix-2026-09-27','golden/FOCUSED_PROOF_SUMMARY.json')]},
];
const checksByEpisode={
  E1:['check-instruction-hygiene.py'],
  E2:['instruction_is_a_natural_product_request','instruction_preserves_natural_human_voice','instruction_leaks_no_grader_machinery','dimensions_cover_every_graded_requirement','criteria_are_independent_and_noncontradictory','global_browser_gate_is_present_and_correct_in_every_dimension','floor_is_low_for_shells_mocks_and_stuffing','gates_apply_before_shaping_and_carry_no_reward_mass','dimension_and_criterion_weights_are_honest','dimension_prompts_are_accurate_and_consistent'],
  E3:['instruction_is_achievable_and_unambiguous_in_the_environment','dimensions_cover_every_graded_requirement','no_criterion_grades_the_unrequired'],
  E4:['instruction_is_achievable_and_unambiguous_in_the_environment','dimensions_cover_every_graded_requirement'],
  E5:['instruction_states_deliverables_and_runtime_contract','instruction_is_achievable_and_unambiguous_in_the_environment','timeouts_fit_the_work','no_criterion_grades_the_unrequired','criteria_are_independent_and_noncontradictory','criteria_are_outcome_based_and_browser_decidable','criterion_description_is_self_consistent','task_is_distinct_and_authored'],
  E6:['instruction_leaks_no_grader_machinery','criteria_are_independent_and_noncontradictory'],
  E7:['timeouts_fit_the_work','criteria_are_independent_and_noncontradictory'],
  E8:['negative_checks_have_positive_controls','criterion_description_is_self_consistent'],
};
const witnessDetails={
  E1:['Six ordinary IDs collided on nine public-text lines. One static check flag, not nine independently failed checks.'],
  E2:['Natural product request: spec/test-rulebook voice and missing owner/use case.','Human voice: overly formal uniform prose; overlaps the prior writing issue but owns another check flag.','Grader machinery: literal verifier files remained in security notes; ID renaming never addressed this text.','Coverage: Function/WebAssembly/Worker/dynamic-import refusals; stale rename; dirty New/import transitions; Auto-run-OFF import; case-sensitive title pairs.','Independence: export/import; origin isolation/unsupported execution; in-app/native dirty warnings; four error-reporting paths.','Global prerequisites: health-only Constraints and workspace-only Render admitted a dead runner or no real server library.','Floor: editor/indent/pane/theme3/49.5 could cross the0.05 floor, giving an analytic0.3364 with0.75 presentation. This was not a measured model score.','Gates and weight honesty: the same weak-gate/cheap-shell witness was reported under multiple check IDs; it is not three separate application bugs.','Dimension prompt consistency: Constraints copied Render and tested reachability rather than its actual backing requirement.'],
  E3:['The stop-versus-supersede explanation was ambiguous; a correct app could cancel A when B starts without emitting a separate supersession notification.','The criterion nevertheless required that unrequested supersession notice. This is the same concrete cause under a second check ID.','The private-file confidentiality promise had no HTTP observation; a whole-working-directory static server could pass the previous UI checks.'],
  E4:['The completed preview lifecycle was unspecified after the first five-second budget, yet later click behavior was expected. Public wording now distinguishes initial Run, completed interaction, pending callbacks and invalidated execution.','A few Tab stops plus shortcut tests did not show that examples and saved snippets could be selected without a pointer.'],
  E5:['Deliverables/runtime: theme/host controls were required to respond during a literal infinite loop, although post-termination usability was the product promise.','Deliverables/runtime and achievability: editor escape documentation was demanded; an app with working native Escape-then-Tab but no help label could falsely fail.','Workload: judge-written private-file classification, network instrumentation construction, repeated recovery save/reload chains and a late restart added work. The repair supplied a tested network recipe, removed redundant mutations and moved restart early; hosted timing remained unmeasured.','Unrequired grading: the same during-loop responsiveness and mandatory escape-help requirements were removed; fixed named-route privacy expectations were made explicit in that repair, later exposing the exact-probe leakage defect.','Independence: dispatch shared one score with delayed click/key/input; original-run shared-budget behavior shared a score with pending-interaction nonextension and redundant persistence legs.','Browser decidability: the privacy classifier required source/package/database-body interpretation while the judge otherwise forbade implementation inspection.','Browser decidability: network denial required a real successful unrestricted tool control; ad-hoc instrumentation or DNS/CORS failure could not prove blocking. The repair supplied the actual MCP setup/count/cleanup recipe and incomplete-evidence handling.','Self-consistency: measuring a valid app delay but observing OFF/cancel for a fixed two seconds could miss a run at2.1s; use max(3s, measured delay+1s).','Self-consistency: replay of an old request proves stale server refusal but cannot prove a live dirty editor retained its draft. Use two actual pages and UI conflict/recovery; stale-rename checks own server invariants separately.','Distinct/authored: short product metadata, hard difficulty and Local library badge replaced scaffolding/style contamination.'],
  E6:['Leakage/undercoverage: public exact /app.db,/server.js,/package.json reservations and explicit exclusion of other paths let deny-only-three pass while companion/package/repository files leaked.','Restart depended on separately graded Duplicate/Delete, so missing Duplicate could also lose restart credit.','Normal deletion, stale-delete preservation and no deleted-identity upsert were bundled; missing stale protection could erase earned normal-delete credit.'],
  E7:['Timeout-fit risk remained: long multi-leg rubric and unmeasured full judge work; source review, not a demonstrated timed-out Oracle.','Import/exact transfer could work while server filename validation failed.','Title trimming, collision behavior and case-sensitive title coexistence could work or fail independently.','Automatic startup and separate unchanged built-in examples could work independently.','Language dispatch could work while CSS retained old handlers; independent feature credit was still bundled.'],
  E8:['Auto-run OFF silence could pass when automatic execution was entirely dead; require real enabled automatic execution and later deliberate execution of the same pending source.','CSS marker silence could pass after the preview/button was deleted, hidden or disabled; require original live handler, retained document and available button, then an actual click.','S06 successful standalone delivery without resolved public role satisfied both the ambiguous/incomplete branch and the unconditional exposure branch. Ordered terminal decisions now exclude competing verdicts.'],
};
for(const e of episodes){e.reported_check_ids=checksByEpisode[e.id];e.flagged_check_occurrences=e.reported_check_ids.length;e.distinct_witness_details=witnessDetails[e.id];e.check_id_source='Preserved local transcripts plus parent screenshot cross-check in this review. Parent explicitly confirmed E3 achievement/ambiguity + coverage + unrequired; E4 achievement/ambiguity + coverage; E8 controls + self-consistency. No platform-run metadata inferred.';}
const recurrence=Object.keys(checksByEpisode).reduce((acc,id)=>{for(const check of checksByEpisode[id])(acc[check]??=[]).push(id);return acc;},{});
const checkRecurrence=Object.entries(recurrence).map(([check_id,episode_ids])=>({check_id,occurrences:episode_ids.length,episode_ids})).sort((a,b)=>b.occurrences-a.occurrences||a.check_id.localeCompare(b.check_id));
const flaggedCount=episodes.reduce((sum,e)=>sum+e.flagged_check_occurrences,0);assert.equal(flaggedCount,30);assert.equal(checkRecurrence.length,19);
const output={created_at:new Date().toISOString(),scope:'Read-only Colderwater history reconstruction. No task/ZIP edits, runtime rerun or provider call. Local report prose is attributed, not authenticated platform export.',archives_verified:archives,documented_feedback_episodes:episodes,feedback_episode_count_is_not_verified_submission_count:true,repeat_and_regression_analysis:repeatAnalysis,events_not_counted_as_platform_rounds:excludedEvents,nondeterminism:{demonstrated:false,identical_zip_and_qc_version_and_settings_differing_result_pairs_found:0,platform_run_ids_found:[],platform_qc_versions_found:[],platform_settings_records_found:[],run_outputs_top_level_directories:fs.readdirSync('run-outputs',{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name),colderwater_run_outputs_directory_found:false,raw_platform_export_found:false,limitation:'No such pair was found in inspected saved artifacts; this is not proof that platform judgments are deterministic. Screenshots summarized in local documents do not preserve complete input/run metadata.',required_evidence_to_establish_variation:'Two preserved original QC outputs bound to exactly the same uploaded ZIP hash, QC version/build, model/settings and invocation conditions, with different findings. No such comparable pair is available.'},current_readiness_boundary:{archive_sha256:byDir['positive-controls-fix-2026-09-27'].sha256,known_open:'Full150-minute/9000-second LLM judge completion, hosted Oracle/model scores and private platform acceptance remain unmeasured; current local report explicitly retains timeout-fit Not exercised/P1.',evidence:source('positive-controls-fix-2026-09-27','QC_FINAL.md')},source_kind_warning:'qc_final_findings.json and QC_FINAL.xlsx are locally authored disposition reports. Their complete53/48 inventories do not mean the private platform checkers ran.'};
output.flag_count={reported_check_occurrences:flaggedCount,distinct_check_ids:checkRecurrence.length,quality_check_ids:18,static_check_ids:1,episode_occurrence_counts:episodes.map(e=>({episode:e.id,count:e.flagged_check_occurrences})),not_a_unique_bug_count:true,source:'Parent rechecked the supplied screenshots; local documents preserve the witness details. Eight episodes are still not authenticated run IDs.'};
output.check_id_recurrence=checkRecurrence;
fs.writeFileSync(path.join(__dirname,'history_evidence.json'),JSON.stringify(output,null,2)+'\n');
const link=p=>`[${p.split('/').at(-1)}](../${p.slice(base.length+1)})`;
const lines=['# Colderwater QC history and repeat-finding evidence','',
'The retained evidence supports repeated findings across changed task versions. It does **not** establish different platform results for identical ZIP bytes, QC version and settings. Eight feedback episodes are described below; this is not a verified count of submissions. Original platform run IDs, QC-version/settings records and complete screenshot exports are absent from this review. Local QC workbooks are attributed local reviews, not platform exports.','',
'## Retained archive sequence','',
'Every ZIP below was rehashed read-only and matched its saved manifest. All retained primary archives contain50 files and preserve Functional weight49.5. Exact changed/added/removed file lists are in the JSON companion.','',
'| Local revision | ZIP SHA prefix | Functional rows | What changed |','|---|---|---:|---|',...archives.map(a=>`| ${a.directory} | ${a.sha256.slice(0,12)} | ${a.functional_criteria} | ${a.change_summary} |`),'',
'## Check counts and recurrence','',
'The parent rechecked the supplied screenshots: **30 flagged check occurrences across8 episodes, involving19 distinct IDs (18 quality checks and1 static check)**. The episode counts are1+10+3+2+8+2+2+2. These are check occurrences, not30 distinct concrete bugs. Several checks describe the same underlying witness.','',
'| Check ID | Occurrences | Episodes |','|---|---:|---|',...checkRecurrence.map(r=>`| ${r.check_id} | ${r.occurrences} | ${r.episode_ids.join(', ')} |`),'',
'## Documented platform-feedback episodes','',
...episodes.flatMap(e=>[`### ${e.id} — ${e.flagged_check_occurrences} flagged checks`,``, `Archive linkage: ${e.archive_linkage}`, '', 'Check IDs: '+e.reported_check_ids.join(', ')+'.','', ...e.distinct_witness_details.map(f=>'- '+f),'',`Repair: ${e.repair_summary}`,'',`Sources: ${e.evidence.map(r=>link(r.path)).join(', ')}.`, '']),
'## Why a check name appeared again','',
...repeatAnalysis.flatMap(r=>[`**${r.topic} — ${r.classification}.** ${r.detail}`,'',`Evidence: ${r.evidence.map(e=>link(e.path)).join(', ')}.`, '']),
'## Events that are not additional platform rounds','',
...excludedEvents.map(e=>'- **'+e.event+':** '+e.reason),'',
'## What can be said about nondeterminism','',
'No Colderwater directory exists under run-outputs, and the independent content search found no Colderwater platform-run artifact there. The ten-failure screenshot transcript lacks an uploaded ZIP hash, run ID, QC version and settings. Later reports provide explicit or contextual version links, but still no comparable pair of original platform results.','',
'Therefore, “the checker changed its mind on the same submission” is unsupported by these files. Reviewer variability remains possible; it is not measured here. Changed ZIPs, different concrete counterexamples under broad check IDs, known local review omissions and documented regressions already explain the observed history without requiring a nondeterminism claim.','',
'The current663e report still carries timeout fit as Not exercised/P1. Source/browser checks support bounded claims, while full hosted Oracle quality and150-minute LLM orchestration remain unmeasured. This history alone cannot guarantee that a last attempt will pass.','',
'Read history_evidence.json for full archive hashes, exact file deltas, source hashes, evidence confidence and the distinction between reported feedback and proven platform-run metadata.',''];
fs.writeFileSync(path.join(__dirname,'history_evidence.md'),lines.join('\n'));
console.log(JSON.stringify({archives:archives.length,feedback_episodes:episodes.length,identical_input_platform_variation_pairs:0,json:ref(path.relative(root,path.join(__dirname,'history_evidence.json')).replaceAll('\\','/')),markdown:ref(path.relative(root,path.join(__dirname,'history_evidence.md')).replaceAll('\\','/'))},null,2));
