'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');
const dbPath=`/tmp/gridforge-test-${process.pid}.sqlite`;process.env.GRIDFORGE_DB=dbPath;
const {app,db}=require('../server');let server,base;
test.before(async()=>{server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}`});
test.after(()=>{server.close();db.close();for(const x of [dbPath,dbPath+'-wal',dbPath+'-shm'])try{fs.unlinkSync(x)}catch{}});
async function request(path,opts){const r=await fetch(base+path,opts);return {status:r.status,data:await r.json()}}
test('seed is present exactly once',async()=>{let x=await request('/api/bootstrap');assert.equal(x.status,200);assert.equal(x.data.workbook.title,'Northwind Operations Plan');assert.equal(x.data.revision,1);assert.equal(db.prepare('select count(*) n from workbooks').get().n,1);assert.equal(db.prepare('select count(*) n from revisions').get().n,1)});
test('save merges disjoint cells and rejects same-cell conflict',async()=>{let x=(await request('/api/bootstrap')).data;let a=structuredClone(x.workbook);a.sheets[0].cells.F2='alpha';let s1=await request('/api/workbooks/ops-plan/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseRevision:1,userId:'riley',workbook:a})});assert.equal(s1.status,200);assert.equal(s1.data.revision,2);let b=structuredClone(x.workbook);b.sheets[0].cells.G2='beta';let s2=await request('/api/workbooks/ops-plan/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseRevision:1,userId:'morgan',workbook:b})});assert.equal(s2.status,200);assert.equal(s2.data.workbook.sheets[0].cells.F2,'alpha');assert.equal(s2.data.workbook.sheets[0].cells.G2,'beta');let c=structuredClone(x.workbook);c.sheets[0].cells.F2='collision';let s3=await request('/api/workbooks/ops-plan/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseRevision:1,userId:'priya',workbook:c})});assert.equal(s3.status,409);assert.deepEqual(s3.data.conflicts,['F2'])});
test('unchanged and malformed saves create no revision',async()=>{let x=(await request('/api/bootstrap')).data,n=db.prepare('select count(*) n from revisions').get().n;let same=await request('/api/workbooks/ops-plan/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseRevision:x.revision,userId:'riley',workbook:x.workbook})});assert.equal(same.status,200);assert.equal(same.data.unchanged,true);let bad=structuredClone(x.workbook);bad.title='Attack';let r=await request('/api/workbooks/ops-plan/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseRevision:x.revision,userId:'riley',workbook:bad})});assert.equal(r.status,400);assert.equal(db.prepare('select count(*) n from revisions').get().n,n)});
