const assert=require('node:assert/strict'),fs=require('node:fs');
const S=require('/app/lib/scoring'),G=require('/app/lib/game'),F=require('/assets/club/scored-hands').SCORED_HANDS,P=require('/assets/club/practice-deals.json');
const results=[];function check(name,fn){fn();results.push({name,passed:true});console.log('PASS',name);}
check('all forty supplied hand totals',()=>{assert.equal(F.length,40);for(const [i,f] of F.entries())assert.equal(S.scoreHand(f.hand,f.cut,f.crib).total,f.total,'fixture '+(i+1));});
function permutations(a){if(!a.length)return [[]];return a.flatMap((c,i)=>permutations(a.filter((_,j)=>i!==j)).map(t=>[c,...t]));}
check('all 24 input permutations of all forty hands',()=>{for(const f of F)for(const hand of permutations(f.hand))assert.equal(S.scoreHand(hand,f.cut,f.crib).total,f.total);});
function fresh(id){const p=P[id],g=G.deal('a',()=>.5);g.hands={a:p.a.slice(),b:p.b.slice()};g.stock=[p.cut];for(const seat of ['a','b'])assert(!G.discard(g,seat,p[seat].slice(4)).error);return g;}
check('practice deals use thirteen distinct valid cards',()=>{for(const p of Object.values(P)){const all=[...p.a,...p.b,p.cut];assert.equal(new Set(all).size,13);assert(all.every(S.isCard));}});
check('twenty-nine overlapping breakdown and crib flush',()=>{assert.deepEqual(S.scoreHand(F[0].hand,F[0].cut,false).breakdown,{fifteens:16,pairs:12,runs:0,flush:0,nobs:1});assert.equal(S.scoreHand(F[7].hand,F[7].cut,true).breakdown.flush,0);});
check('invalid hand/pile inputs and duplicate cards refuse',()=>{for(const [hand,cut] of [[['ZZ','2S','3H','4D'],'5C'],[['AS','AS','3H','4D'],'5C'],[['AS','2S','3H'],'5C'],[F[0].hand,null]])assert(S.scoreHand(hand,cut).error);assert(S.scorePlay(['ZZ'],'5C').error);assert(S.scorePlay(['5C'],'5C').error);});
check('pegging fifteens, thirty-one, unsorted run, pairs and maximum',()=>{assert.equal(S.scorePlay(['5S'],'TH').points,2);assert.equal(S.scorePlay(['5S','TH','6H','7H','AC'],'2S').points,2);assert.equal(S.scorePlay(['5S','7H'],'6D').points,3);assert.equal(S.scorePlay(['5S'],'5H').points,2);assert.equal(S.scorePlay(['5S','5H'],'5D').points,8);assert.equal(S.scorePlay(['5S','5H','5D'],'5C').points,12);assert(S.scorePlay(['TS','TH','TD'],'2S').error);});
check('complete deterministic hand, between state, alternating dealer',()=>{const g=fresh('pegging'),scores={a:0,b:0};assert(!G.cutCard(g,scores).error);for(const [seat,card] of [['b','5S'],['a','7H'],['b','6H'],['a','TH'],['b','AC'],['a','2S'],['b','9D'],['a','3S']])assert(!G.play(g,seat,card,scores).error);assert.equal(g.phase,'show');assert.equal(g.count,0);assert.equal(scores.a,3);assert.equal(scores.b,3);G.show(g,scores);assert.equal(g.phase,'between');assert.deepEqual(g.shown.map(s=>s.label),['non-dealer','dealer','crib']);const after={...scores};G.nextHand(g,()=>.5);assert.equal(g.dealer,'b');assert.equal(g.hand_no,2);assert.deepEqual(scores,after);});
check('go credits last player once and resets to the other with cards',()=>{const g=fresh('go'),scores={a:0,b:0};G.cutCard(g,scores);for(const [seat,card] of [['b','TH'],['a','TS'],['b','9H']])assert(!G.play(g,seat,card,scores).error);assert.equal(g.count,0);assert.equal(g.turn,'a');assert.equal(scores.b,1);assert.equal(scores.a,2);});
check('his heels is immediate, capped, separate from show',()=>{const g=fresh('heels'),scores={a:120,b:113};G.cutCard(g,scores);assert.equal(g.phase,'over');assert.deepEqual(scores,{a:121,b:113});assert.equal(g.shown.length,0);assert.equal(g.events.at(-1).points,2);});
check('pegging finish is capped and stops before later cards',()=>{const g=fresh('pegging'),scores={a:120,b:0};G.cutCard(g,scores);G.play(g,'b','5S',scores);G.play(g,'a','TH',scores);assert.equal(g.phase,'over');assert.equal(scores.a,121);const copy=JSON.stringify(g);assert(G.play(g,'b','6H',scores).error);assert.equal(JSON.stringify(g),copy);});
check('show stops at nondealer, dealer and crib boundaries',()=>{for(const target of ['non-dealer','dealer','crib']){const g=fresh('pairs');g.cut=P.pairs.cut;g.phase='show';const order=[{who:'b',cards:g.kept.b},{who:'a',cards:g.kept.a},{who:'a',cards:g.crib,crib:true}];const totals=order.map(x=>S.scoreHand(x.cards,g.cut,!!x.crib).total);const index=['non-dealer','dealer','crib'].indexOf(target);const scores={a:0,b:0};scores[order[index].who]=121-totals[index]-(index===2?totals[1]:0);G.show(g,scores);assert.equal(g.phase,'over');assert.equal(g.shown.length,index+1);assert.equal(scores[order[index].who],121);}});
fs.writeFileSync('/evidence/unit-results.json',JSON.stringify({results},null,2));
