const assert=require('node:assert/strict'),fs=require('node:fs'),{randomUUID}=require('node:crypto'),{execFileSync}=require('node:child_process');
const {chromium}=require('/usr/local/lib/node_modules/@playwright/mcp/node_modules/playwright');
const results=[],base='http://127.0.0.1:3000';let browser,page,ada,nora,ben,review,attempt,zero;
async function check(name,fn){await fn();results.push({name,passed:true});console.log('PASS '+name);}
async function api(path,t,body,method){const r=await fetch(base+path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',Connection:'close',...(t?{Authorization:'Bearer '+t}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert(r.ok,JSON.stringify(data));return data;}
async function login(who){return (await api('/api/auth/login',null,{email:who+'@coursemark.example',password:'Coursemark!2026'})).token;}
async function write(path,t,body={},method='POST'){return api(path,t,{...body,expected_revision:(await api('/api/me',t)).revision,operation_id:randomUUID()},method);}
async function snapshot(){const o={};for(const path of ['/api/me','/api/assessments','/api/attempts','/api/audit','/api/outcomes'])o[path]=await api(path,ada);return o;}
async function action(selector,path){const waiting=page.waitForResponse(r=>r.url().endsWith(path)&&r.request().method()!=='GET');await page.locator(selector).click();const r=await waiting;await r.finished();assert(r.ok(),await r.text());}
async function exception(student,assessment,excused){await page.locator('#edit-exception').click();const f=page.locator('#exception-form');await f.locator('[name=student_id]').selectOption(student);await f.locator('[name=assessment_id]').selectOption(assessment);await f.locator('[name=excused]').selectOption(String(excused));await f.locator('[name=reason]').fill('Documented review accommodation');await action('#exception-form button[type=submit]','/api/outcome-exceptions');await page.locator('#exception-dialog').waitFor({state:'hidden'});}
function record(step,payload){execFileSync('python3',['/tests/evidence.py','record','functional','_handoff',step],{input:JSON.stringify(payload)});}
(async()=>{
 ada=await login('ada.mensah');nora=await login('nora.kim');ben=await login('ben.okafor');
 await check('complete handoff has multi-row hidden worksheet, all ledger states and numeric final together',async()=>{
  const created=await write('/api/assessments',ada,{course_id:'BIO-214',title:'Shared written review',opens_at:'2026-09-02T11:00:00Z',due_at:'2026-09-02T13:00:00Z',duration_minutes:30,max_attempts:1});review=created.assessment.id;
  for(const [prompt,label] of [['Explain sampling bias','Explains bias'],['Give a fair sampling method','Explains method']])await write('/api/assessments/'+review+'/items',ada,{kind:'written',prompt,points:2,criterion_label:label});
  await write('/api/assessments/'+review+'/publish',ada);const started=await write('/api/assessments/'+review+'/start',nora);attempt=started.attempt.id;await write('/api/attempts/'+attempt+'/submit',nora);
  const at=(await api('/api/attempts',ada)).attempts.find(a=>a.id===attempt);for(const item of at.items)for(const c of item.rubric)await write('/api/attempts/'+attempt+'/grades/'+c.id,ada,{score:1,feedback:'A clear explanation'},'PUT');
  zero=(await api('/api/outcomes',ada)).assessments.find(a=>a.title==='UI arithmetic zero').id;
  browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});page=await browser.newPage({viewport:{width:1280,height:800}});await page.goto(base);await page.locator('#login-email').fill('ada.mensah@coursemark.example');await page.locator('#login-password').fill('Coursemark!2026');await page.locator('#login-form button[type=submit]').click();await page.locator('#app-view').waitFor({state:'visible'});await page.locator('.tab[data-view=gradebook]').click();await page.locator('#open-outcomes').click();
  await page.locator('#edit-weights').click();for(const field of await page.locator('#weight-rows input').all()){const id=await field.getAttribute('data-weight');await field.fill(String(id==='A-01'||id===review?10:id==='A-03'||id===zero?40:0));}await action('#weight-form button[type=submit]','/api/outcome-weights');await page.locator('#weight-dialog').waitFor({state:'hidden'});await exception('user_3',review,true);await exception('user_4','A-01',false);
  const ledger=await api('/api/outcomes',ada),nr=ledger.rows.find(r=>r.student.id==='user_3'),br=ledger.rows.find(r=>r.student.id==='user_4');const cell=(r,id)=>r.cells.find(c=>c.assessment_id===id);
  assert.equal(nr.final_percentage,56);assert.equal(br.final_percentage,null);assert.equal(cell(br,'A-01').state,'pending');assert.equal(cell(br,review).state,'missing');assert.equal(cell(nr,review).state,'excused');assert(cell(nr,review).reason);assert.equal(cell(br,zero).state,'released');assert.equal(cell(br,zero).awarded,0);assert.equal(cell(br,'A-04').state,'unweighted');
  const own=await api('/api/attempts',nora),hidden=own.attempts.find(a=>a.id===attempt);assert(hidden.total_score===null||hidden.total_score===undefined);const ownLedger=await api('/api/outcomes',ben);assert.equal(ownLedger.rows[0].cells.find(c=>c.assessment_id==='A-01').awarded,null);
  await page.screenshot({path:'/evidence/handoff-all-states-desktop.png',animations:'disabled'});record('ready',{review_assessment_id:review,review_attempt_id:attempt,zero_assessment_id:zero,ledger,required_states_verified:true,rubric_rows:at.items.flatMap(i=>i.rubric.map(c=>c.id))});
 });
 await check('handoff survives process restart and helper returns the exact latest verified state',async()=>{
  const before=await snapshot();execFileSync('bash',['/tests/app-lifecycle.sh','restart']);assert.deepEqual(await snapshot(),before);record('final',{review_assessment_id:review,review_attempt_id:attempt,zero_assessment_id:zero,ledger:before['/api/outcomes'],required_states_verified:true});const latest=JSON.parse(execFileSync('python3',['/tests/evidence.py','read','functional','_handoff','--latest'],{encoding:'utf8'}));assert(JSON.stringify(latest).includes(attempt));
 });
 await check('Polish and Visual can inspect excused multi-row worksheet and batch at both viewports without consuming fixture',async()=>{
  await page.keyboard.press('Escape');const before=await snapshot();
  for(const viewport of [{width:1280,height:800},{width:375,height:812}]){await page.setViewportSize(viewport);await page.locator('[data-worksheet="'+attempt+'"]').click();await page.locator('#worksheet-dialog').waitFor({state:'visible'});assert.equal(await page.locator('#worksheet-rows fieldset').count(),2);await page.locator('#worksheet-rows [data-include]').first().uncheck();assert(await page.locator('#worksheet-rows textarea').first().isDisabled());assert(!(await page.locator('#worksheet-rows textarea').last().isDisabled()));await page.locator('#worksheet-rows [data-include]').first().check();await page.screenshot({path:'/evidence/handoff-worksheet-'+viewport.width+'.png',animations:'disabled'});await page.keyboard.press('Escape');await page.locator('#worksheet-dialog').waitFor({state:'hidden'});
   await page.locator('#open-release-batch').click();await page.locator('#release-batch-dialog').waitFor({state:'visible'});await page.locator('[data-release-choice="'+attempt+'"]').check();await action('#preview-release','/api/release-plans');await page.locator('#release-preview').filter({hasText:'Shared written review'}).waitFor();assert(await page.locator('#commit-release').isEnabled());await page.screenshot({path:'/evidence/handoff-preview-'+viewport.width+'.png',animations:'disabled'});await page.locator('[data-release-choice="'+attempt+'"]').uncheck();assert(await page.locator('#commit-release').isDisabled());await page.locator('[data-release-choice="'+attempt+'"]').check();await action('#preview-release','/api/release-plans');await page.keyboard.press('Escape');await page.locator('#release-batch-dialog').waitFor({state:'hidden'});assert.deepEqual(await snapshot(),before);
  }
 });
 await browser.close();fs.writeFileSync('/evidence/handoff-runtime.json',JSON.stringify({kind:'Local handoff/runtime checks; not platform grades',results},null,2));
})().catch(async error=>{console.error(error);results.push({passed:false,error:String(error),stack:error.stack});fs.writeFileSync('/evidence/handoff-runtime.json',JSON.stringify({results},null,2));if(browser)await browser.close();process.exitCode=1;});
