const assert=require('node:assert/strict');
const fs=require('node:fs');
const {randomUUID}=require('node:crypto');
const {execFileSync}=require('node:child_process');
const {chromium}=require('/usr/local/lib/node_modules/@playwright/mcp/node_modules/playwright');
const base='http://127.0.0.1:3000',results=[];
let browser,a,l,n,b,acceptedReceipt,rejectedReceipt,revokedNoraToken;
async function check(name,fn){await fn();results.push({name,passed:true});console.log('PASS '+name);}
async function api(path,token,body,method){const r=await fetch(base+path,{method:method||(body===undefined?'GET':'POST'),headers:{'Content-Type':'application/json',Connection:'close',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,data:await r.json()};}
const emails={ada:'ada.mensah',luis:'luis.ortega',nora:'nora.kim',ben:'ben.okafor'};
async function login(who){const r=await api('/api/auth/login',null,{email:emails[who]+'@coursemark.example',password:'Coursemark!2026'});assert.equal(r.status,200);return r.data.token;}
async function get(path,t){const r=await api(path,t);assert.equal(r.status,200,JSON.stringify(r));return r.data;}
async function mutation(path,t,body={},method='POST'){const me=await get('/api/me',t),payload={...body,expected_revision:me.revision,operation_id:randomUUID()};const r=await api(path,t,payload,method);assert(r.status===200||r.status===201,JSON.stringify(r));assert.equal(r.data.revision,me.revision+1);return {...r,body:payload,path,method};}
async function snap(t){return {me:await get('/api/me',t),assessments:await get('/api/assessments',t),attempts:await get('/api/attempts',t),audit:await get('/api/audit',t)};}
async function reject(path,t,body={},method='POST'){const before=await snap(t);const r=await api(path,t,{...body,expected_revision:before.me.revision,operation_id:randomUUID()},method);assert(r.status>=400&&r.status<500,JSON.stringify(r));assert.deepEqual(await snap(t),before);return r;}
const draft=title=>({course_id:'BIO-214',title,opens_at:'2026-09-03T09:00:00Z',due_at:'2026-09-03T11:00:00Z',duration_minutes:25,max_attempts:2});
const attempts=async t=>(await get('/api/attempts',t)).attempts;
async function uiLogin(page,who){await page.goto(base);await page.locator('#login-email').fill(emails[who]+'@coursemark.example');await page.locator('#login-password').fill('Coursemark!2026');await page.locator('#login-form button[type=submit]').click();await page.locator('#app-view').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#courses-list').children.length>0);}
async function uiMutation(page,locator,ending){const w=page.waitForResponse(r=>r.url().endsWith(ending)&&r.request().method()!=='GET');await locator.click();const r=await w;await r.finished();return r;}
async function uiDraft(page,title){await page.locator('.tab[data-view=assessments]').click();await page.locator('#new-assessment').click();const f=page.locator('#assessment-form');await f.locator('[name=title]').fill(title);await f.locator('[name=opens_at]').fill('2026-09-03T09:00');await f.locator('[name=due_at]').fill('2026-09-03T11:00');return f;}
(async()=>{
 await check('authentication, exact seed import and first-start expiry',async()=>{
  assert.equal((await api('/api/me')).status,401);assert.equal((await api('/api/auth/login',null,{email:'ada.mensah@coursemark.example',password:'wrong'})).status,401);
  [a,l,n,b]=await Promise.all(['ada','luis','nora','ben'].map(login));assert.equal(new Set([a,l,n,b]).size,4);assert.equal(a.length,64);
  const s=await snap(a);assert.equal(s.me.reference_moment,'2026-09-02T12:00:00Z');assert.deepEqual(s.assessments.assessments.map(x=>x.id).sort(),['A-01','A-02','A-03','A-04']);assert.equal(s.attempts.attempts.length,4);
  const exp=s.attempts.attempts.find(x=>x.id==='AT-103');assert.equal(exp.assessment_id,'A-04');assert.equal(exp.status,'graded');assert.equal(exp.objective_score,5);assert.equal(exp.submitted_at,'2026-09-02T12:00:00Z');assert.equal(s.audit.events.filter(x=>x.action==='auto_submitted'&&x.entity_id==='AT-103').length,1);
 });
 await check('accommodation timing, deadline extensions and exact-expiry answer lock',async()=>{
  const ns=(await get('/api/assessments',n)).assessments.find(x=>x.id==='A-01');assert.equal(ns.effective_due_at,'2026-09-02T13:00:00.000Z');assert.equal(ns.effective_duration_minutes,60);assert.equal(ns.attempt.expires_at,'2026-09-02T12:30:00.000Z');assert.equal(ns.attempt.status,'in_progress');assert(!('objective_score' in ns.attempt));
  const bs=(await get('/api/assessments',b)).assessments.find(x=>x.id==='A-01');assert.equal(bs.effective_due_at,'2026-09-02T14:00:00.000Z');assert.equal(bs.effective_duration_minutes,45);
  await reject('/api/attempts/AT-103/answers',b,{answers:[{item_id:'I-05',value:'Woody bark'}]},'PATCH');await reject('/api/attempts/AT-103/submit',b,{answers:[{item_id:'I-05',value:'Woody bark'}]});assert.equal((await attempts(a)).find(x=>x.id==='AT-103').objective_score,5);
 });
 await check('role filtering, answer-key privacy and forbidden writes',async()=>{
  assert.deepEqual((await attempts(l)).map(x=>x.id).sort(),['AT-100','AT-101','AT-103']);for(const t of [n,b]){const aa=(await get('/api/assessments',t)).assessments;assert(!aa.some(x=>x.id==='A-02'));const items=(await get('/api/assessments/A-01/items',t)).items;assert(items.every(x=>!Object.hasOwn(x,'answer')));}
  assert.equal((await get('/api/assessments/A-01/items',a)).items[0].answer,'Transect');assert((await attempts(n)).every(x=>x.student.id==='user_3'));assert((await attempts(b)).every(x=>x.student.id==='user_4'));
  await reject('/api/assessments',l,draft('Forbidden'));await reject('/api/attempts/AT-100/answers',b,{answers:[{item_id:'I-01',value:'Transect'}]},'PATCH');await reject('/api/attempts/AT-101/grades/RC-3',n,{score:1},'PUT');await reject('/api/attempts/AT-102/grades/RC-3',l,{score:1},'PUT');
 });
 await check('availability, active-attempt and attempt-limit guards',async()=>{
  await reject('/api/assessments/A-02/start',n);await reject('/api/assessments/A-03/start',b);await reject('/api/assessments/A-04/start',b);await reject('/api/assessments/A-01/start',n);
 });
 browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});
 await check('real browser Nora save/reload/submit with derived private score',async()=>{
  const p=await browser.newPage();await uiLogin(p,'nora');await p.locator('.tab[data-view=assessments]').click();assert.match(await p.locator('#assessments-list').innerText(),/\+15 minutes accommodation/);await p.screenshot({path:'/evidence/nora-accommodation-assessments.png',fullPage:true});await p.locator('.tab[data-view=attempts]').click();await p.locator('#attempts-list [data-open-attempt="AT-100"]').click();await p.locator('#attempt-dialog').waitFor({state:'visible'});
  await p.locator('#attempt-dialog input[value="Transect"]').check();await p.locator('#attempt-dialog textarea').fill('Observer placement can favor the trail edge.');const before=(await get('/api/me',n)).revision;assert.equal((await uiMutation(p,p.locator('#save-answers'),'/answers')).status(),200);await p.waitForFunction(()=>!document.querySelector('#save-answers').disabled);assert.equal((await get('/api/me',n)).revision,before+1);
  await p.reload();await p.locator('#app-view').waitFor({state:'visible'});await p.locator('.tab[data-view=attempts]').click();await p.locator('#attempts-list [data-open-attempt="AT-100"]').click();assert(await p.locator('#attempt-dialog input[value="Transect"]').isChecked());assert.equal(await p.locator('#attempt-dialog textarea').inputValue(),'Observer placement can favor the trail edge.');
  assert.equal((await uiMutation(p,p.locator('#attempt-form button[type=submit]'),'/submit')).status(),200);await p.locator('#attempt-dialog').waitFor({state:'hidden'});assert.equal((await attempts(a)).find(x=>x.id==='AT-100').objective_score,4);assert(!Object.hasOwn((await attempts(n)).find(x=>x.id==='AT-100'),'objective_score'));await reject('/api/attempts/AT-100/submit',n);await p.close();
 });
 await check('rubric score invalid types/bounds, partial completion and replacement',async()=>{
  for(const score of [undefined,null,true,false,'','abc',-1,3])await reject('/api/attempts/AT-101/grades/RC-3',l,{score,feedback:'invalid'},'PUT');
  let r=await mutation('/api/attempts/AT-101/grades/RC-3',l,{score:1,feedback:'temporary'},'PUT');assert.equal(r.data.attempt.status,'submitted');r=await mutation('/api/attempts/AT-101/grades/RC-3',l,{score:2,feedback:'Names the changing limit'},'PUT');assert.equal(r.data.attempt.grades.length,1);assert.equal(r.data.attempt.rubric_score,2);
 });
 await check('real browser grading completion, release replay and private feedback',async()=>{
  const p=await browser.newPage();await uiLogin(p,'luis');await p.locator('.tab[data-view=gradebook]').click();await p.locator('[data-grade="AT-101"]').click();await p.locator('[data-score="RC-4"]').fill('2.5');await p.locator('[data-feedback="RC-4"]').fill('Connects it to seasonal resources');assert.equal((await uiMutation(p,p.locator('[data-save-grade="RC-4"]'),'/grades/RC-4')).status(),200);await p.close();
  const graded=(await attempts(a)).find(x=>x.id==='AT-101');assert.equal(graded.status,'graded');assert.equal(graded.objective_score,0);assert.equal(graded.total_score,4.5);assert(!Object.hasOwn((await attempts(b)).find(x=>x.id==='AT-101'),'grades'));
  const adaPage=await browser.newPage();await uiLogin(adaPage,'ada');await adaPage.locator('.tab[data-view=gradebook]').click();const baseline=await snap(a);const response=await uiMutation(adaPage,adaPage.locator('[data-release="AT-101"]'),'/api/attempts/AT-101/release');const request=response.request(),serialized=request.postData(),headers=request.headers();const r={status:response.status(),data:await response.json(),path:'/api/attempts/AT-101/release',method:request.method(),body:JSON.parse(serialized)};assert.equal(r.status,200);assert.equal(r.data.revision,baseline.me.revision+1);acceptedReceipt=r;const before=await snap(a);const replay=await adaPage.request.fetch(request.url(),{method:request.method(),headers:{'content-type':headers['content-type'],authorization:headers.authorization},data:serialized});const replayResult={status:replay.status(),data:await replay.json()};assert.deepEqual(replayResult,{status:r.status,data:r.data});assert.deepEqual(await snap(a),before);fs.writeFileSync('/evidence/exact-release-ui-replay.json',JSON.stringify({method:r.method,url:request.url(),serializedBody:serialized,original:{status:r.status,data:r.data},replay:replayResult,revisionBefore:baseline.me.revision,revisionAfter:before.me.revision,stateUnchanged:true,sameSession:true},null,2));await adaPage.close();
  const released=(await attempts(b)).find(x=>x.id==='AT-101');assert.equal(released.total_score,4.5);assert.deepEqual(released.grades.map(x=>x.feedback),['Names the changing limit','Connects it to seasonal resources']);await reject('/api/attempts/AT-101/release',a);await reject('/api/attempts/AT-101/grades/RC-4',l,{score:1},'PUT');assert(!(await attempts(n)).some(x=>x.id==='AT-101'));
 });
 let canopy;
 await check('draft validation, written/MC question rules and publication lifecycle',async()=>{
  await reject('/api/assessments',a,{...draft('invalid'),due_at:'2026-09-01T00:00:00Z'});const r=await mutation('/api/assessments',a,draft('Canopy survey practical'));canopy=r.data.assessment.id;
  await reject(`/api/assessments/${canopy}/publish`,a);await reject(`/api/assessments/${canopy}/items`,a,{kind:'multiple_choice',prompt:'Duplicate',points:1,options:['A','A'],answer:'A'});
  await mutation(`/api/assessments/${canopy}/items`,a,{kind:'written',prompt:'Explain one canopy closure bias.',points:4,criterion_label:'Links cover to detection'});await mutation(`/api/assessments/${canopy}/publish`,a);await reject(`/api/assessments/${canopy}/publish`,a);await reject(`/api/assessments/${canopy}/items`,a,{kind:'written',prompt:'Late',points:1,criterion_label:'Late'});await reject(`/api/assessments/${canopy}/start`,n);
 });
 await check('successful start, exact timing and duplicate/start retry safety',async()=>{
  const r=await mutation('/api/assessments/A-01/start',b);assert.equal(r.data.attempt.expires_at,'2026-09-02T12:45:00.000Z');assert.equal(r.data.attempt.started_at,'2026-09-02T12:00:00Z');assert.equal(r.data.attempt.assigned_grader_id,'user_2');const before=await snap(b);assert.deepEqual(await api(r.path,b,r.body,r.method),{status:r.status,data:r.data});assert.deepEqual(await snap(b),before);await reject('/api/assessments/A-01/start',b);
 });
 await check('positive MC authoring, staff key read and student key omission',async()=>{
  const r=await mutation('/api/assessments',a,{...draft('Tree identification practice'),opens_at:'2026-09-02T11:00:00Z',due_at:'2026-09-02T13:00:00Z'});const id=r.data.assessment.id;
  await mutation(`/api/assessments/${id}/items`,a,{kind:'multiple_choice',prompt:'Choose the broadleaf tree',points:3,options:['Oak','Pine'],answer:'Oak'});assert.equal((await get(`/api/assessments/${id}/items`,a)).items[0].answer,'Oak');await mutation(`/api/assessments/${id}/publish`,a);const item=(await get(`/api/assessments/${id}/items`,b)).items[0];assert.deepEqual(item.options,['Oak','Pine']);assert(!Object.hasOwn(item,'answer'));
 });
 await check('effective due caps Nora adjusted duration without wall-clock changes',async()=>{
  const r=await mutation('/api/assessments',a,{...draft('Short deadline check'),opens_at:'2026-09-02T11:00:00Z',due_at:'2026-09-02T12:05:00Z',duration_minutes:30,max_attempts:1});const id=r.data.assessment.id;await mutation(`/api/assessments/${id}/items`,a,{kind:'written',prompt:'Name a bias',points:1,criterion_label:'Valid bias'});await mutation(`/api/assessments/${id}/publish`,a);const started=await mutation(`/api/assessments/${id}/start`,n);assert.equal(started.data.attempt.effective_duration_minutes,45);assert.equal(started.data.attempt.expires_at,'2026-09-02T12:05:00.000Z');assert.equal((await attempts(n)).find(x=>x.id===started.data.attempt.id).expires_at,'2026-09-02T12:05:00.000Z');
 });
 await check('audit visibility, newest-first order and exactly-once terminal events',async()=>{
  const events=(await get('/api/audit',a)).events;assert(events.every((x,i)=>!i||events[i-1].id>x.id));for(const [action,id] of [['auto_submitted','AT-103'],['submitted','AT-100'],['released','AT-101'],['published',canopy]])assert.equal(events.filter(x=>x.action===action&&x.entity_id===id).length,1);
  for(const [t,user] of [[n,'user_3'],[b,'user_4']]){const ids=new Set((await attempts(t)).map(x=>x.id));assert((await get('/api/audit',t)).events.every(x=>x.entity_type==='attempt'&&ids.has(x.entity_id)));}
  const assigned=new Set((await attempts(l)).map(x=>x.id));assert((await get('/api/audit',l)).events.every(x=>x.actor_id==='user_2'||(x.entity_type==='attempt'&&assigned.has(x.entity_id))));
 });
 await check('real browser stale tabs, authoritative refresh and rejected receipt replay',async()=>{
  const p=await browser.newPage(),q=await browser.newPage();await uiLogin(p,'ada');await uiLogin(q,'ada');await uiDraft(p,'Transect calibration A');await uiDraft(q,'Transect calibration B');const r=await uiMutation(p,p.locator('#assessment-form button[type=submit]'),'/api/assessments');assert.equal(r.status(),201);await p.locator('#assessment-dialog').waitFor({state:'hidden'});
  const stale=await uiMutation(q,q.locator('#assessment-form button[type=submit]'),'/api/assessments');assert.equal(stale.status(),409);await q.locator('#assessment-error').filter({hasText:'another tab'}).waitFor();assert.match(await q.locator('#assessments-list').innerText(),/Transect calibration A/);
  const request=stale.request(),token=request.headers().authorization.slice(7),body=request.postDataJSON(),response=await stale.json();assert.equal((await uiMutation(q,q.locator('#assessment-form button[type=submit]'),'/api/assessments')).status(),201);await q.locator('#assessment-dialog').waitFor({state:'hidden'});const before=await snap(a);assert.deepEqual(await api('/api/assessments',token,body),{status:409,data:response});assert.deepEqual(await snap(a),before);
  rejectedReceipt={path:'/api/assessments',token,body,response};const original=r.request().postDataJSON();assert.equal((await api('/api/assessments',r.request().headers().authorization.slice(7),{...original,title:'Different'})).status,409);await p.close();await q.close();
 });
 await check('real browser pending duplicate draft guard',async()=>{
  const p=await browser.newPage();await uiLogin(p,'ada');await uiDraft(p,'Pending-once draft');const before=await get('/api/me',a);let release,seen;const held=new Promise(r=>release=r),arrived=new Promise(r=>seen=r);await p.route('**/api/assessments',async route=>{if(route.request().method()!=='POST')return route.continue();const r=await route.fetch();seen();await held;await route.fulfill({response:r});});const button=p.locator('#assessment-form button[type=submit]');await button.click();await arrived;await button.click({force:true});release();await p.locator('#assessment-dialog').waitFor({state:'hidden'});assert.equal((await get('/api/me',a)).revision,before.revision+1);assert.equal((await get('/api/assessments',a)).assessments.filter(x=>x.title==='Pending-once draft').length,1);await p.close();
 });
 await check('real browser all views, mobile/dialog keyboard and reduced motion',async()=>{
  const p=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];p.on('pageerror',e=>errors.push(String(e)));await uiLogin(p,'ada');
  for(const name of ['courses','assessments','attempts','gradebook','audit']){await p.locator(`.tab[data-view=${name}]`).focus();await p.keyboard.press('Enter');await p.locator(`.tab[data-view=${name}][aria-current=page]`).waitFor();assert.equal(await p.locator(`.tab[data-view=${name}]`).getAttribute('aria-current'),'page');assert(await p.locator(`#view-${name}`).isVisible());}
  await p.screenshot({path:'/evidence/coursemark-desktop.png',fullPage:true});await p.setViewportSize({width:375,height:812});for(const name of ['courses','assessments','attempts','gradebook','audit']){await p.locator(`.tab[data-view=${name}]`).click();await p.locator(`.tab[data-view=${name}][aria-current=page]`).waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  await uiDraft(p,'Invalid mobile draft');await p.locator('#assessment-form [name=due_at]').fill('2026-09-01T00:00');assert.equal((await uiMutation(p,p.locator('#assessment-form button[type=submit]'),'/api/assessments')).status(),400);assert(await p.locator('#assessment-dialog').isVisible());assert(await p.locator('#assessment-error').innerText());
  await p.keyboard.press('Tab');assert(await p.evaluate(()=>document.querySelector('#assessment-dialog').contains(document.activeElement)));await p.keyboard.press('Escape');await p.locator('#assessment-dialog').waitFor({state:'hidden'});assert(await p.evaluate(()=>document.activeElement!==document.body));await p.emulateMedia({reducedMotion:'reduce'});assert(await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches));await p.screenshot({path:'/evidence/coursemark-mobile.png',fullPage:true});assert.deepEqual(errors,[]);await p.close();
 });
 await check('account-wide revocation, warm signout and reauthentication isolation',async()=>{
  const p=await browser.newPage(),q=await browser.newPage();await uiLogin(p,'nora');await uiLogin(q,'nora');const t1=await p.evaluate(()=>sessionStorage.getItem('coursemark_bearer_token')),t2=await q.evaluate(()=>sessionStorage.getItem('coursemark_bearer_token'));assert.notEqual(t1,t2);revokedNoraToken=t1;const before=await snap(n);await p.locator('#logout').click();await p.locator('#login-view').waitFor({state:'visible'});assert.equal((await api('/api/me',t1)).status,401);assert.equal((await api('/api/me',t2)).status,401);await q.reload();await q.locator('#login-view').waitFor({state:'visible'});n=await login('nora');assert.deepEqual(await snap(n),before);await p.close();await q.close();
 });
 await check('manifest methods/routes and actual lifecycle restart persistence/receipts',async()=>{
  const manifest=fs.readFileSync('/app/APP_MANIFEST.md','utf8');assert.match(manifest,/```bash\nnode \/app\/server.js/);assert.match(manifest,/SQLite path: \/app\/coursemark.db/);
  const before=await Promise.all([a,l,n,b].map(snap));execFileSync('bash',['/tests/app-lifecycle.sh','restart']);assert.deepEqual(await Promise.all([a,l,n,b].map(snap)),before);const blank=await browser.newPage();assert.equal(blank.url(),'about:blank');const refused=await blank.request.get(base+'/api/me',{headers:{Authorization:'Bearer '+revokedNoraToken}});assert.equal(refused.status(),401);const rejectedBody=await refused.json();assert(!rejectedBody.user&&!rejectedBody.courses);const positive=await blank.request.get(base+'/api/me',{headers:{Authorization:'Bearer '+n}});assert.equal(positive.status(),200);assert.equal((await positive.json()).user.id,'user_3');fs.writeFileSync('/evidence/revoked-after-restart-from-blank.json',JSON.stringify({pageURL:blank.url(),requestURL:base+'/api/me',refusalStatus:refused.status(),refusalBody:rejectedBody,positiveStatus:positive.status(),positiveActor:'user_3'},null,2));await blank.close();const r=acceptedReceipt;assert.deepEqual(await api(r.path,a,r.body,r.method),{status:r.status,data:r.data});assert.deepEqual(await api(rejectedReceipt.path,rejectedReceipt.token,rejectedReceipt.body),{status:409,data:rejectedReceipt.response});assert.deepEqual(await Promise.all([a,l,n,b].map(snap)),before);
 });
 await browser.close();fs.writeFileSync('/evidence/regressions.json',JSON.stringify({kind:'unpaid local API/browser checks, not an Oracle score',results},null,2));
})().catch(async error=>{console.error(error);results.push({passed:false,error:String(error),stack:error.stack});fs.writeFileSync('/evidence/regressions.json',JSON.stringify({results},null,2));if(browser)await browser.close();process.exitCode=1;});
