const fs=require('fs');
const {spawn}=require('child_process');
const assert=require('assert/strict');
const {chromium}=require('/usr/local/lib/node_modules/@playwright/mcp/node_modules/playwright');
const source='/runs/run-94c32bc4-7dcc-4574-b511-b11e07b71564/patchpad-editor-v3__yeYzfVZ/artifacts/app';
const results={scope:'Focused diagnostic on unchanged exported Gemini source in cached patchpad-preflight-tests:2.0.9; not an official regrade.',checks:[]};
let server,browser;
async function main(){
 fs.cpSync(source,'/tmp/gemini-app',{recursive:true,filter:p=>!/(?:\.db(?:-wal|-shm)?|node_modules)$/.test(p)});
 server=spawn('node',['server.js'],{cwd:'/tmp/gemini-app',env:{...process.env,PORT:'3000'},stdio:'inherit'});
 for(let i=0;;i++){try{if((await fetch('http://localhost:3000')).ok)break;}catch{}assert(i<100);await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1280,height:800},permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();
 page.setDefaultTimeout(10000);
 page.on('dialog',dialog=>dialog.accept());
 const fresh=async()=>{await page.goto('http://localhost:3000');await page.locator('.patchpad-line').first().waitFor();};
 const copy=async()=>{await page.keyboard.press('Control+a');await page.keyboard.press('Control+c');return page.evaluate(()=>navigator.clipboard.readText());};
 const saved=async()=>{const response=await page.request.get('http://localhost:3000/api/reports/incident-alpha');return response.json();};
 const history=async()=>{const response=await page.request.get('http://localhost:3000/api/reports/incident-alpha/revisions');return response.json();};
 await fresh();
 const baseline=await saved();
 await page.screenshot({path:'/out/gemini-desktop.png'});
 const starts=await page.locator('.patchpad-line').evaluateAll(lines=>lines.slice(0,3).map(e=>{const range=document.createRange();range.setStart(e.firstChild,0);range.setEnd(e.firstChild,1);const r=range.getBoundingClientRect();return {x:r.x+.1,y:r.y+r.height/2,text:e.textContent};}));
 for(let i=0;i<starts.length;i++){if(i)await page.keyboard.down('Alt');await page.mouse.click(starts[i].x,starts[i].y);if(i)await page.keyboard.up('Alt');}
 assert.equal(await page.locator('.patchpad-caret').count(),3);
 const carets=await page.locator('.patchpad-caret').evaluateAll(es=>es.map(e=>({left:e.style.left,top:e.style.top})));
 const focusAfterClick=await page.evaluate(()=>document.activeElement.className);
 await page.locator('#btn-find').click();await page.keyboard.press('Escape');
 const focusBeforeTyping=await page.evaluate(()=>document.activeElement.className);
 assert.match(focusBeforeTyping,/patchpad-input-capture/);
 await page.keyboard.type('MULTI',{delay:50});
 const typed=await page.locator('.patchpad-line').evaluateAll(es=>es.slice(0,3).map(e=>e.textContent));
 assert.deepEqual(typed.map(t=>t.replace('MULTI','')),starts.map(s=>s.text));
 await page.keyboard.press('Control+z');
 const undone=await page.locator('.patchpad-line').evaluateAll(es=>es.slice(0,3).map(e=>e.textContent));
 assert.deepEqual(undone,typed.map(t=>t.replace('MULTI','MULT')));
 assert.deepEqual(await saved(),baseline);
 results.checks.push({name:'multi-caret typing grouping',verdict:'APP_DEFECT_REPRODUCED',real_input:true,focusAfterClick,focusBeforeTyping,carets,before:starts.map(s=>s.text),typed,after_one_undo:undone,server_unchanged:true});
 await fresh();
 const focus=()=>page.locator('.patchpad-input-capture').focus();
 await focus();await page.keyboard.press('Control+End');await page.keyboard.type(' REVISION-HISTORY-A',{delay:25});
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/save')&&r.request().method()==='POST'),page.locator('#btn-save').click()]);
 const a=await saved();assert.equal(a.current_revision,2);
 await focus();await page.keyboard.press('Control+End');await page.keyboard.type(' REVISION-HISTORY-B',{delay:25});
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/save')&&r.request().method()==='POST'),page.locator('#btn-save').click()]);
 const b=await saved();assert.equal(b.current_revision,3);const beforeHistory=await history();
 await page.locator('#btn-history').click();
 await page.locator('.btn-preview-rev[data-rev="1"]').click();
 await page.locator('#preview-modal').waitFor({state:'visible'});
 const preview=await page.locator('.preview-line-text').allTextContents();
 assert.equal(preview.join('\n').replaceAll('\u00a0',''),baseline.content);
 assert.deepEqual(await saved(),b);assert.deepEqual(await history(),beforeHistory);
 await page.locator('#btn-restore-preview').click();
 await page.locator('#preview-modal').waitFor({state:'hidden'});
 const dirty=await page.locator('#save-badge').textContent();
 assert.match(dirty,/unsaved/i);
 const restored=await copy();assert.equal(restored,baseline.content);
 await page.keyboard.press('Control+z');
 const afterUndo=await copy();assert.equal(afterUndo,b.content);
 assert.deepEqual(await saved(),b);assert.deepEqual(await history(),beforeHistory);
 results.checks.push({name:'revision-1 preview, unsaved Restore, single Undo',verdict:'FOCUSED_PATH_PASSED',real_input:true,saved_revisions:[a.current_revision,b.current_revision],preview_exact:true,dirty,restore_exact:true,undo_exact:true,server_and_history_unchanged:true});
}
main().catch(e=>{results.error=e.stack;process.exitCode=1;}).finally(async()=>{fs.writeFileSync('/out/gemini-reproduction.json',JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results,null,2));if(browser)await browser.close();if(server)server.kill();});
