'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=process.cwd(),base=path.relative(root,__dirname).replaceAll('\\','/'),review=base.slice(0,-'/golden'.length);
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p))),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const ref=p=>({path:p,sha256:sha(p)}),write=(name,j)=>fs.writeFileSync(path.join(__dirname,name),JSON.stringify(j,null,2)+'\n');
const manifestPath=base+'/frozen_final_inputs.json',inputs=read(manifestPath),stage=read(review+'/staged_candidate.json'),archive=read(review+'/review-candidate/candidate_manifest.json');
const runNames={full:'run-golden-20260927-143456',feedback:'run-golden-feedback-20260927-143836',import:'run-server-extension-20260927-143108',title:'run-title-nocase-20260927-143109',css:'run-css-handlers-20260927-143109',restart:'run-restart-no-duplicate-delete-20260927-143109'};
const runs=Object.fromEntries(Object.entries(runNames).map(([k,v])=>[k,read(base+'/'+v+'/RESULTS.json')]));
const references=Object.fromEntries(Object.entries(runNames).map(([k,v])=>[k,ref(base+'/'+v+'/RESULTS.json')]));
const sourceFiles={...inputs.solution_files};
for(const[relative,digest]of Object.entries(sourceFiles)){
  assert.equal(sha(stage.staged_task+'/solution/'+relative),digest);
  assert.equal(sha('projects/colderwater-playground-devtools/solution/'+relative),digest);
  assert.equal(archive.source_sha256['solution/'+relative],digest);
}
assert.equal(sha(review+'/review-candidate/'+archive.archive),archive.sha256);
for(const[relative,digest]of Object.entries({'tests/scored/functional/judge.toml':inputs.functional_sha256,'tests/scored/functional/prompt.md':inputs.prompt_sha256,'tests/app_context.md':inputs.context_sha256})){
  assert.equal(sha(stage.staged_task+'/'+relative),digest);assert.equal(sha('projects/colderwater-playground-devtools/'+relative),digest);assert.equal(archive.source_sha256[relative],digest);
}
for(const run of Object.values(runs)){assert.equal(run.manifest_sha256,sha(manifestPath));assert.equal(run.functional_sha256,inputs.functional_sha256);assert.equal(run.prompt_sha256,inputs.prompt_sha256);assert.equal(run.paid_provider,false);assert.equal(run.network,'none');}
for(const name of ['full','feedback','restart'])for(const[relative,digest]of Object.entries(runs[name].actual_app_files))assert.equal(sourceFiles['app/'+relative],digest);
assert.equal(runs.full.passed,false);assert.deepEqual(runs.full.failed_fact_keys,['S23.stale_save_draft_recovery','S33.import_unsupported_extension']);assert.deepEqual(runs.full.missing_fact_keys,[]);assert(runs.feedback.passed);
const corrected=new Set(runs.full.failed_fact_keys),criteria=inputs.criteria.map(c=>{
  assert.equal(c.evidence_keys.length,1);const key=c.evidence_keys[0],name=corrected.has(key)?'feedback':'full',fact=runs[name].facts[key];assert(fact?.product_pass);assert(fact.criterion_ids.includes(c.id));
  return {id:c.id,weight:c.weight,criterion_sha256:runs.full.criterion_hashes[c.id],criterion_source_block_sha256:c.source_block_sha256,description:c.description,evidence_key:key,protocol_sha256:inputs.scenarios[key.split('.')[0]].protocol_sha256,status:'fresh local observation passed',oracle_verdict:false,evidence:{...references[name],json_pointer:'/facts/'+key},prior_failed_probe:corrected.has(key)?{...references.full,json_pointer:'/facts/'+key,reason:'The first predicate inspected status alone. Targeted retry inspected newly added visible feedback from this action.'}:undefined};
});
assert.equal(criteria.length,88);assert.equal(new Set(criteria.map(c=>c.id)).size,88);
for(const row of criteria.filter(row=>row.evidence_key==='S26.duplicate_edit_independence'))row.fixture_deviation='Behavior-equivalent Original edit marker: driver used original-edited-independently; frozen protocol says original-independently-edited. Same identity/revision/read-back and bidirectional copy-isolation observations were made; exact literal execution is not claimed.';
const stats=run=>{
  const phases=['pre','post'].map(p=>run[p]).filter(Boolean),actions=phases.flatMap(p=>p.actions),waits=phases.flatMap(p=>p.explicit_waits),counts={};for(const action of actions)counts[action.kind]=(counts[action.kind]||0)+1;
  return {wall_seconds:run.wall_seconds,phase_process_wall_seconds:Object.fromEntries(['pre','post'].filter(p=>run[p]).map(p=>[p,run[p].outer_process_wall_seconds])),restart_wall_seconds:run.restart?.wall_seconds,recorded_actions:actions.length,recorded_action_counts:counts,ordinary_manual_run_activations:counts.manual_run||0,keyboard_run_activations:counts.shortcut_run||0,total_manual_run_activations:(counts.manual_run||0)+(counts.shortcut_run||0),explicit_behavioral_waits:waits.length,explicit_wait_requested_seconds:waits.reduce((s,w)=>s+w.requested_ms,0)/1000,explicit_wait_observed_seconds:waits.reduce((s,w)=>s+w.observed_ms,0)/1000,recorded_network_responses:phases.reduce((s,p)=>s+p.network.length,0),browser_errors:phases.flatMap(p=>p.browser_errors),note:'These helper-ledger actions are not an exhaustive count of low-level UI/API steps or MCP round trips. Deadline polling also consumes real time; it is included in wall time but not explicit wait totals. Nested timings must not be added together.'};
};
const variants=[];
for(const name of ['import','title','css']){
  const run=runs[name],result=run.variant.variant_results;assert(run.passed&&result.all_expectations_matched&&result.expected_defect_observed);
  const defects=result.observations.filter(r=>r.product_pass===false);assert(defects.length&&defects.every(r=>r.expected_product_pass===false&&r.expectation_matched));
  variants.push({name:run.case,status:'expected defect and working sibling outcomes observed',wall_seconds:run.wall_seconds,evidence:references[name],failed_product_outcomes: defects.map(r=>({fact_key:r.fact_key,criterion_ids:r.criterion_ids,product_pass:r.product_pass,expectation_matched:r.expectation_matched})),working_product_outcomes:result.observations.filter(r=>r.product_pass===true).map(r=>({fact_key:r.fact_key,criterion_ids:r.criterion_ids})),source_files:run.actual_app_files});
}
assert(runs.restart.passed&&runs.restart.restart.actual_calls===1);
for(const phase of ['pre','post'])assert.deepEqual(runs.restart[phase].capability_action_counts,{run:0,duplicate:0,delete:0});
variants.push({name:'restart-no-duplicate-delete',status:'restart durability passed with Duplicate/Delete removed before restart and disabled after restart',wall_seconds:runs.restart.wall_seconds,evidence:references.restart,pre_overlay:runs.restart.pre.capability_overlay,post_overlay:runs.restart.post.capability_overlay,pre_control_clicks:runs.restart.pre.capability_action_counts,post_control_clicks:runs.restart.post.capability_action_counts,actual_restart_calls:1});
const map={scope:'All 88 Functional outcomes only; local composite evidence, not an LLM score',created_at:new Date().toISOString(),archive_sha256:archive.sha256,criterion_hash_definition:'SHA-256 of the Python json.dumps(row, sort_keys=True) UTF-8 representation used by launch_workflow.py; source_block_sha256 separately binds the exact TOML criterion block.',functional_sha256:inputs.functional_sha256,prompt_sha256:inputs.prompt_sha256,all_current_criteria:criteria,counts:{fresh_pass:88,reused:0,missing:0,failed_after_targeted_retry:0}};
write('FUNCTIONAL_EVIDENCE_MAP.json',map);
const summary={schema_version:1,created_at:new Date().toISOString(),scope:'Fresh local direct-Playwright Functional proof with actual canonical MCP restart; no provider/platform/LLM judge call',archive_sha256:archive.sha256,pinned_image:'sha256:43757904510bf933d70d209e77077ad0173deb345f61a1477eb106f4e2380f6f',chromium:runs.full.chromium,playwright_mcp:runs.full.mcp,network:'none',user_preview_port_3420_used:false,composite_local_functional_passed:true,oracle_score_claimed:false,full_llm_timing_measured:false,full_single_run_passed:false,coverage:{functional_outcomes:88,functional_weight:49.5,protocols:37,fresh_successful_outcomes:88,historical_reused_functional_outcomes:0,unexercised_functional_outcomes:[],fresh_security_privacy_protocols:['S05','S06','S07'],other_dimensions:'Polish, Visual, Render, and Constraints were not freshly judged by this workflow. No verdict for those dimensions is produced here.'},full_workflow:{evidence:references.full,raw_passed:false,fresh_outcomes:88,raw_passed_outcomes:86,raw_failed_outcomes:[...corrected],timing:stats(runs.full)},targeted_retry:{evidence:references.feedback,raw_passed:true,selected_outcomes:11,corrects:[...corrected],cause:'Both old predicates read status alone even though the useful error is visibly rendered in an alert or console. Revised proof snapshots before and after the actual triggering action and tests only newly added feedback.',timing:stats(runs.feedback)},composite_method:'Use 86 passing facts from the completed full workflow and only the two corrected facts from the separate targeted retry. Preserve every failed raw report. This is not a claim that the full single run passed.',partial_feature_witnesses:variants,failed_attempts:[{evidence:ref(base+'/run-golden-20260927-142745/RESULTS.json'),disposition:'Retained first attempt: implicit option value lookup, CRLF fixture normalization and Export button selector were proof defects. Its post phase ended on an unhandled download waiter. No result from that attempt is used for final positive coverage.'},{evidence:references.full,disposition:'Completed with the two visible-feedback capture defects; used only its 86 passing facts.'}],budget_comparison:{allowance_seconds:9000,measured_full_local_automation_seconds:runs.full.wall_seconds,measured_targeted_retry_seconds:runs.feedback.wall_seconds,interpretation:'Local automation workload is measured. LLM reasoning, snapshots/tool verbosity, provider latency, and complete hosted judge execution are unmeasured; this is not a proof of 150-minute timeout fit.'},references:{inputs:ref(manifestPath),functional_evidence_map:ref(base+'/FUNCTIONAL_EVIDENCE_MAP.json'),candidate_manifest:ref(review+'/review-candidate/candidate_manifest.json'),variant_source_binding:ref(base+'/variants/variant_binding.json')},unresolved_local_functional_failures:[]};
summary.proof_limits=[
  'S26 used a behavior-equivalent Original edit marker (original-edited-independently instead of original-independently-edited). Exact literal protocol execution is not claimed.',
  'S33 golden observations establish successful lowercase/uppercase attribution. They do not exercise the alternative in which uppercase saving fails before lower-case recovery; the direct golden driver would stop that scenario at such a failed positive save.',
  'The four partial-feature witnesses cover their named defect/control pairs, not all possible partially implemented submissions or every allowed UI architecture.'
];
write('RUNTIME_PROOF_SUMMARY.json',summary);
const binding={created_at:new Date().toISOString(),archive_sha256:archive.sha256,solution_files:sourceFiles,solution_file_count:Object.keys(sourceFiles).length,main_and_staged_and_archive_sources_identical:true,inputs:ref(manifestPath),functional_sha256:inputs.functional_sha256,prompt_sha256:inputs.prompt_sha256,context_sha256:inputs.context_sha256,restart_mcp_sha256:inputs.restart_mcp_sha256,restart_script_sha256:inputs.restart_script_sha256,fresh_proofs:references,summary:ref(base+'/RUNTIME_PROOF_SUMMARY.json'),functional_map:ref(base+'/FUNCTIONAL_EVIDENCE_MAP.json'),variants:ref(base+'/variants/variant_binding.json'),historical_reused_functional_proofs:[],notes:['All 23 golden solution files verified identical in final staged candidate, active task, and archive manifest. Golden direct-run actual app file hashes matched manifest.', 'Mutants are disposable local copies. Their per-run app hashes are preserved; their expected product defects are not mislabeled passes.', 'Canonical MCP restart was actually invoked in each restart proof; ordinary browser actions use direct pinned Playwright.']};
write('golden_evidence_binding.json',binding);
const markdown=`# Fresh local Functional evidence\n\nAll 88 Functional outcomes have successful fresh local observations across the 37 shared protocols. This is composite evidence: the complete 90.16-second workflow passed 86 outcomes, then a separate 11.94-second targeted run corrected two proof predicates that had read only status text. The original failed reports remain unchanged. The targeted checks observed new visible conflict/import errors caused by their own actions and retained the exact draft checks.\n\nFour partial-feature witnesses passed their expected observations: working import beside broken server extension validation; working title trimming beside wrong case-insensitive uniqueness; working language dispatch beside retained CSS-preview handlers; and durable restart with Duplicate/Delete unavailable and zero Run/Duplicate/Delete clicks. Deliberate defects remain recorded as product failures.\n\nThe full run made 50 ordinary Run activations plus one keyboard Run (51 manual activations), one actual canonical MCP restart, and nine privacy navigations. Twenty explicit bounded waits consumed 37.96 seconds. Deadline polling and other action latency are included in the 90.16-second wall time. Helper action counts are not an exhaustive count of UI steps or MCP round trips.\n\nSecurity/privacy protocols S05-S07 were freshly exercised. No historical Functional observations are reused. This run does not freshly judge Polish, Visual, Render, or Constraints. It does not establish an Oracle score or a full LLM judge runtime; the 9,000-second allowance remains unvalidated by a paid judge run.\n\nCandidate archive: ${archive.sha256}. Browser work used direct Playwright in the pinned offline verifier image; restart used the canonical MCP tool. The live user preview on port 3420 was excluded.\n\nSee RUNTIME_PROOF_SUMMARY.json, FUNCTIONAL_EVIDENCE_MAP.json, and golden_evidence_binding.json for exact hashes and per-outcome evidence pointers.\n`;
fs.writeFileSync(path.join(__dirname,'RUNTIME_PROOF_SUMMARY.md'),markdown+'\nProof limits: S26 used the equivalent Original marker original-edited-independently instead of the protocol literal original-independently-edited. S33 demonstrated the successful uppercase/lowercase paths; it did not exercise a failed-uppercase-save recovery alternative. The four counterexamples cover their named cases, not every partially implemented app.\n');
console.log(JSON.stringify({summary:ref(base+'/RUNTIME_PROOF_SUMMARY.json'),binding:ref(base+'/golden_evidence_binding.json'),functional_map:ref(base+'/FUNCTIONAL_EVIDENCE_MAP.json'),coverage:summary.coverage},null,2));
